(function(){var aa;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ca(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function da(a){return a instanceof Array?a:ca(p(a))}
var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ka=fa,la={construct:"Metrika2",callbackPostfix:"2",version:"3brkhoacvv52iyz5nne7xzv0qg42",host:"mc.yandex.ru"},ma={238419105:1,1522378928:1,2791265539:1,3724710748:1};function na(a,b){return b(a)}function t(a){return function(b){return function(c){return a(b,c)}}}function oa(a){return function(b){return function(c){return a(c,b)}}}var pa=t(function(a,b){return a===b}),qa=t(function(a,b){a(b);return b}),ra=t(na);function u(){}var sa=[];
function ta(a,b){if(!b||"function"!==typeof b)return!1;try{var c=""+b}catch(h){return!1}var d=c.length;if(d>35+a.length)return!1;for(var e=d-13,f=0,g=8;g<d;g+=1){f="[native code]"[f]===c[g]||7===f&&"-"===c[g]?f+1:0;if(12===f)return!0;if(!f&&g>e)break}return!1}function ua(a,b){var c=ta(a,b);b&&!c&&sa.push([a,b]);return c}function va(a,b){return ua(b,a)&&a}function wa(a,b){for(var c=0;c<b.length;c+=1)if(b[c]===a)return c;return-1}var xa;
function ya(a){if(xa)return xa;var b=!1;try{b=[].indexOf&&0===[void 0].indexOf(void 0)}catch(d){}var c=a.Array&&a.Array.prototype&&va(a.Array.prototype.indexOf,"indexOf");return xa=a=b&&c?function(d,e){return c.call(e,d)}:wa}var za=ya(window),Aa=oa(za);function x(a){return a}function Ba(a,b){return b}function Ca(a){return!a}var Da=va(Array.from,"from");function Ea(a){for(var b=a.length,c=[],d=0;d<b;d+=1)c.push(a[d]);return c}function Fa(a){if(Da)try{return Da(a)}catch(b){}return Ea(a)}
function y(a,b){var c=[],d=[];var e=b?b:x;return function(){var f=Fa(arguments),g=e.apply(null,da(f)),h=za(g,d);if(-1!==h)return c[h];f=a.apply(null,da(f));c.push(f);d.push(g);return f}}var Ga=/\./g;function Ha(a){return"string"===typeof a}var Ia=va(String.prototype.indexOf,"indexOf");function Ja(a,b){for(var c=0,d=a.length-b.length,e=0;e<a.length;e+=1){c=a[e]===b[c]?c+1:0;if(c===b.length)return e-b.length+1;if(!c&&e>d)break}return-1}var Ka=Ia?function(a,b){return Ia.call(a,b)}:Ja;
function La(a,b){return Ka(a,b)}function Ma(a,b){return!(!a||-1===Ka(a,b))}function Na(a){return a.replace(/\^/g,"\\^").replace(/\$/g,"\\$").replace(Ga,"\\.").replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\|/g,"\\|").replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/\?/g,"\\?").replace(/\*/g,"\\*").replace(/\+/g,"\\+").replace(/\{/g,"\\{").replace(/\}/g,"\\}")}var Oa=pa(null);function z(a){return"function"===typeof a}var Pa=pa(void 0);function Qa(a){return Pa(a)||Oa(a)}
function Ra(a){return!Oa(a)&&!Pa(a)&&"[object Object]"===Object.prototype.toString.call(a)}function Sa(a,b,c){b=void 0===b?[]:b;c=c||{};var d=b.length,e=a;z(e)&&(e="d",c[e]=a);var f;d?1===d?f=c[e](b[0]):2===d?f=c[e](b[0],b[1]):3===d?f=c[e](b[0],b[1],b[2]):4===d&&(f=c[e](b[0],b[1],b[2],b[3])):f=c[e]();return f}var Ta=va(Function.prototype.bind,"bind");
function Ua(){var a=Fa(arguments);a=p(a);var b=a.next().value,c=a.next().value,d=ca(a);return function(){var e=[].concat(da(d),da(Fa(arguments)));if(Function.prototype.call)return Function.prototype.call.apply(b,[c].concat(da(e)));if(c){for(var f="_b";c[f];)f+="_"+f.length;c[f]=b;e=c[f]&&Sa(f,e,c);delete c[f];return e}return Sa(b,e)}}var Va=Ta?function(){var a=Fa(arguments),b=p(a);a=b.next().value;var c=b.next().value;b=ca(b);return Ta.apply(a,[c].concat(b))}:Ua;
function A(a,b){return Va.apply(null,[b,null].concat(da(a)))}function C(a,b){return Va(b,null,a)}function Wa(a,b){return Va(b[a],b)}function Xa(a){return Wa("test",a)}var Ya=va(Array.prototype.reduce,"reduce");function Za(a,b,c){for(var d=0,e=c.length;d<e;)b=a(b,c[d],d),d+=1;return b}var E=Ya?function(a,b,c){return Ya.call(c,a,b)}:Za;function $a(a,b){return A([a,b],E)}function F(){var a=Fa(arguments),b=a.shift();return function(){var c=b.apply(null,arguments);return E(na,c,a)}}
var ab=t(A),bb=t(Wa),cb=Object.prototype.hasOwnProperty;function db(a,b){return Qa(a)?!1:cb.call(a,b)}function G(a,b){return a?E(function(c,d){if(Qa(c))return c;try{return c[d]}catch(e){}return null},a,b.split(".")):null}var H=oa(G),eb=H("length");function fb(a){var b=void 0===b?{}:b;if(!a||1>a.length)return b;E(function(c,d,e){if(e===a.length-1)return c;e===a.length-2?c[d]=a[e+1]:db(c,d)||(c[d]={});return c[d]},b,a);return b}
function gb(a,b){var c=G(b,a),d=G(b,"constructor.prototype."+a)||c;try{if(d&&d.apply)return function(){return d.apply(b,arguments)}}catch(e){return c}return d}function hb(a,b,c){return c?a:b}var ib=A([1,null],hb),jb=A([1,0],hb),kb=Boolean,lb=va(Array.prototype.filter,"filter");function mb(a,b){return Za(function(c,d,e){a(d,e)&&c.push(d);return c},[],b)}var nb=lb?function(a,b){return lb.call(b,a)}:mb,ob=C(kb,nb),pb=t(nb);function I(a,b,c){return Array.prototype.includes.call(b,a,c)}var qb=oa(I);
function rb(a){return"[object Array]"===Object.prototype.toString.call(a)}var sb=va(Array.isArray,"isArray"),tb=sb?function(a){return sb(a)}:rb;function ub(a){return a?tb(a)?a:Da?Da(a):"number"===typeof a.length&&0<=a.length?Ea(a):[]:[]}var vb=y(ya),wb=H("0");function xb(a){return a.splice(0,a.length)}
var yb=y(function(a){var b=G(a,"navigator")||{};a=G(b,"userAgent")||"";b=G(b,"vendor")||"";return{sb:-1<Ka(b,"Apple"),Ob:a}}),zb=y(H("navigator.userAgent")),Ab=/Firefox\/([0-9]+)/i,Bb=y(function(a){var b=G(a,"document.documentElement.style"),c=G(a,"InstallTrigger");a=-1!==(G(a,"navigator.userAgent")||"").toLowerCase().search(Ab);Ab.lastIndex=0;return!(!(b&&"MozAppearance"in b)||Qa(c))||a});
function Cb(){var a=Array.prototype.map;if(!Bb(window))return!0;try{a.call({0:!0,length:-Math.pow(2,32)+1},function(){throw 1;})}catch(b){return!1}return!0}var Db=va(Array.prototype.map,"map");function Eb(a,b){return E(function(c,d,e){c.push(a(d,e));return c},[],b)}var J=Db&&Cb()?function(a,b){return b&&0<b.length?Db.call(b,a):[]}:Eb,Fb=t(J),Gb=oa(J),Hb=va(Array.prototype.some,"some");function Ib(a,b){for(var c=0;c<b.length;c+=1)if(c in b&&a.call(b,b[c],c))return!0;return!1}
var Jb=Hb?function(a,b){return Hb.call(b,a)}:Ib;function Kb(a){try{return parseInt(a,10)}catch(b){return null}}var Mb=oa(parseInt),Nb=Mb(10),Ob=Mb(2),Pb=va(Object.keys,"keys");function Qb(a){var b=[],c;for(c in a)db(a,c)&&b.push(c);return b}
var Rb=function(a){return function(b){return b?a(b):[]}}(Object.entries),L=Pb?function(a){return Pb(a)}:Qb,M=Object.assign,Sb=t(function(a,b){return M({},a,b)}),Tb=y(F(H("String.fromCharCode"),C("fromCharCode",ua),Ca)),Ub=y(F(zb,Xa(/ipad|iphone|ipod/i))),Vb=y(function(a){a=yb(a);var b=a.Ob;return a.sb&&!b.match("CriOS")}),Wb=Xa(/Android.*Version\/[0-9][0-9.]*\sChrome\/[0-9][0-9.]|Android.*Version\/[0-9][0-9.]*\s(?:Mobile\s)?Safari\/[0-9][0-9.]*\sChrome\/[0-9][0-9.]*|; wv\).*Chrome\/[0-9][0-9.]*\sMobile/),
Xb=Xa(/; wv\)/),Yb=y(function(a){a=zb(a);return Xb(a)||Wb(a)}),Zb="other none unknown wifi ethernet bluetooth cellular wimax mixed".split(" "),$b=y(function(a){var b=G(a,"navigator.connection.type");if(Pa(b))return null;a=vb(a)(b,Zb);return-1===a?b:""+a}),ac=y(F(H("document.addEventListener"),Ca)),bc=y(function(a){var b=G(a,"navigator")||{};return E(function(c,d){return c||G(b,d)},"",["language","userLanguage","browserLanguage","systemLanguage"])}),cc=y(function(a){var b=G(a,"navigator")||{};a=bc(a);
Ha(a)||(a="",b=G(b,"languages.0"),Ha(b)&&(a=b));return a.toLowerCase().split("-")[0]}),dc=y(function(a){return(G(a,"top")||a)!==a}),ec=y(H("top.contentWindow")),fc=y(function(a){var b=!1;try{b=a.navigator.javaEnabled()}catch(c){}return b});function gc(a){return I("prerender",J(C(G(a,"document"),G),["webkitVisibilityState","visibilityState"]))}
var hc=y(function(a){var b=zb(a)||"",c=b.match(/Mac OS X ([0-9]+)_([0-9]+)/);c=c?[+c[1],+c[2]]:[0,0];b=b.match(/iPhone OS ([1-9]+)_([0-9]+)/);return 14<=(b?+b[1]:0)?!0:(Ub(a)||10<c[0]||10===c[0]&&13<=c[1])&&Vb(a)}),ic=/Edg\/(\d+)\./,jc=y(function(a){var b;if(!(b=hc(a)))a:{if(Bb(a)&&(b=zb(a).match(Ab))&&b.length){b=68<=+b[1];break a}b=!1}if(!b)a:{if((a=zb(a))&&(a=a.match(ic))&&1<a.length){b=79<=Nb(a[1]);break a}b=!1}return b}),kc=la.construct,lc=la.host,mc=ac(window),N={Xb:24226447,Sb:26302566,Zb:51533966,
Uc:65446441,ia:"https:",da:"2063",bc:kc,Wb:mc?512:2048,Ub:mc?512:2048,Vb:mc?100:400,Vc:100,Yb:"noindex"},nc=pa("1");function oc(a,b,c,d){var e={};return Ra(a)?a:(e.id=a,e.type=c,e.defer=d,e.params=b,e)}function pc(a){return E(function(b,c){var d=p(c),e=d.next().value,f=d.next().value;d=f.Wa;f=a[f.V];b[e]=d?d(f):f;return b},{},Rb(qc))}var O=y(function(a){return a.id+":"+a.L});
function rc(a){a=a.Ya=a.Ya||{};var b=a._metrika=a._metrika||{};return{O:function(c,d){db(b,c)||(b[c]=d);return this},A:function(c,d){b[c]=d;return this},m:function(c,d){var e=b[c];return db(b,c)||Pa(d)?e:d}}}var P=y(rc),Q=window.Promise,sc=["http.0.st..rt.","network error occurred","send beacon","Content Security Policy","DOM Exception 18"],tc;function uc(a){this.message=a}
var vc=function(a){return function(b,c){c=void 0===c?!1:c;if(tc)var d=new tc(b);else ua("Error",a.Error)?(tc=a.Error,d=new a.Error(b)):(tc=uc,d=new tc(b));c&&(d.unk=!0);return d}}(window),wc=Xa(RegExp("^http."));function xc(a){throw a;}function yc(a,b){for(var c="",d=0;d<b.length;d+=1)c+=""+(d?a:"")+b[d];return c}
var zc=va(Array.prototype.join,"join"),R=zc?function(a,b){return zc.call(b,a)}:yc,Ac=t(R),Bc=y(function(a){a=!(!a.addEventListener||!a.removeEventListener);return{Fc:a,C:a?"addEventListener":"attachEvent",Ca:a?"removeEventListener":"detachEvent"}});function Cc(a,b,c,d,e,f){a=Bc(a);var g=a.C,h=a.Ca;f=f?h:g;if(b[f])if(a.Fc)if(e)b[f](c,d,e);else b[f](c,d);else b[f]("on"+c,d)}
var Dc=y(function(a){var b=!1;if(!a.addEventListener)return b;try{var c=Object.defineProperty({},"passive",{get:function(){b=!0;return 1}});a.addEventListener("test",u,c)}catch(d){}return b}),Ec=t(function(a,b){if(null!==b)return a?M({capture:!0,passive:!0},b||{}):!!b}),Fc=y(function(a){var b=Dc(a),c=Ec(b),d={};return M(d,{C:function(e,f,g,h){J(function(k){var l=c(h);Cc(a,e,k,g,l,!1)},f);return Va(d.ra,d,e,f,g,h)},ra:function(e,f,g,h){J(function(k){var l=c(h);Cc(a,e,k,g,l,!0)},f)}})});
function Gc(a){return G(a,"performance")||G(a,"webkitPerformance")}function Hc(a){a=Gc(a);var b=G(a,"timing.navigationStart"),c=G(a,"now");c&&(c=Va(c,a));return[b,c]}function Ic(a,b){var c=p(b||Hc(a)),d=c.next().value;c=c.next().value;return!isNaN(d)&&z(c)?Math.round(c()+d):a.Date.now?a.Date.now():(new a.Date).getTime()}function Jc(a){return(10>a?"0":"")+a}
function Kc(a){var b=Fc(a),c=Hc(a),d={l:a,fb:0,S:c,oc:Ic(a,c)},e=p(c);c=e.next().value;e=e.next().value;c&&e||b.C(a,["beforeunload","unload"],function(){0===d.fb&&(d.fb=Ic(a,d.S))});return ra(d)}function S(a){var b=a.fb;return 0!==b?b:Ic(a.l,a.S)}function Lc(a){return Math.floor(S(a)/1E3/60)}function Mc(a){return Math.round(S(a)/1E3)}function Nc(a){var b=p(a.S),c=b.next().value;b=b.next().value;a=c&&b?b():S(a)-a.oc;return Math.round(a)}var T=y(Kc);function Oc(a){return a.bb||a.za.length<=a.R}
function Pc(a){a.R=a.za.length}function Qc(a){a.bb=!0}function Rc(a){a.bb=!1}function Sc(a){Oc(a)&&xc(vc("i"));var b=a.vb(a.za[a.R]);a.R+=1;return b}var Tc=t(function(a,b){for(var c=[];!Oc(b);){var d=Sc(b);a(d,function(e){return e(b)});c.push(d)}return c});function Uc(a,b){return function(c){var d=T(a),e=d(S);return Tc(function(f,g){d(S)-e>=b&&g(Qc)})(c)}}
function Vc(a){for(var b=!0,c={};!Oc(a)&&b;c={Va:void 0})b=!1,c.Va=function(){b=!0;a.R+=1},a.vb(a.za[a.R],function(d){return function(){(0,d.Va)()}}(c)),b||(a.R+=1,c.Va=C(a,Vc))}function Wc(a,b){return ra({za:a,vb:b||x,bb:!1,R:0})}function Xc(a,b,c){c=void 0===c?!1:c;return new Q(function(d,e){function f(k,l){l();d()}var g=a.slice();g.push({H:f,ca:f});var h=Wc(g,function(k,l){var m=c?k.H:k.ca;if(m)try{m(b,l)}catch(n){h(Pc),e(n)}else l()});h(Vc)})}
function Yc(a){try{return encodeURIComponent(a)}catch(b){}a=R("",nb(function(b){return 55296>=b.charCodeAt(0)},a.split("")));return encodeURIComponent(a)}function Zc(a){var b="";try{b=decodeURIComponent(a)}catch(c){}return b}function $c(a){return a?F(Fb(function(b){var c=p(b.split("="));b=c.next().value;c=c.next().value;return[b,Qa(c)?void 0:Zc(c)]}),$a(function(b,c){var d=p(c),e=d.next().value;d=d.next().value;b[e]=d;return b},{}))(a.split("&")):{}}
function ad(a){return a?F(Rb,$a(function(b,c){var d=p(c),e=d.next().value;d=d.next().value;Pa(d)||Qa(d)||b.push(e+"="+Yc(d));return b},[]),Ac("&"))(a):""}function bd(a,b,c){var d=Pa(c);Pa(b)&&d?(d=1,b=1073741824):d?d=1:(d=b,b=c);return a.Math.floor(a.Math.random()*(b-d))+d}function cd(a,b,c){return function(){var d=P(arguments[0]),e=c?"global":"m2063",f=d.m(e,{}),g=G(f,a);g||(g=y(b),f[a]=g,d.A(e,f));return g.apply(null,arguments)}}var dd=qb([26812653]),ed=y(F(H("id"),dd),O),fd="hash host hostname href pathname port protocol search".split(" ");
function U(a){return E(function(b,c){var d=G(a,"location."+c);b[c]=d?""+d:"";return b},{},fd)}var gd="ru by kz az kg lv md tj tm uz ee fr lt com co.il com.ge com.am com.tr com.ru".split(" "),hd=/(?:^|\.)(?:(ya\.ru)|(?:yandex)\.(\w+|com?\.\w+))$/,id=y(function(a){return(a?a.replace(/^www\./,""):"").toLowerCase()}),jd=y(function(a){a=U(a).hostname;var b=!1;a&&(b=-1!==a.search(hd));return b}),kd=/^\s+|\s+$/g,ld=va(String.prototype.trim,"trim");
function md(a){return a?ld?ld.call(a):(""+a).replace(kd,""):""}var nd=t(function(a,b){return b.replace(a,"")})(/\D/g),od=["metrika_enabled"],pd=[];function qd(a,b){var c=rd;return!pd.length||I(b,od)?!0:E(function(d,e){return d&&e(a,c,b)},!0,pd)}function sd(a){try{var b=a.document.cookie;if(!Qa(b)){var c={};J(function(d){var e=p(d.split("="));d=e.next().value;e=e.next().value;c[md(d)]=md(Zc(e))},(b||"").split(";"));return c}}catch(d){}return null}var td=cd("gsc",sd);
function rd(a,b){var c=td(a);return c?c[b]||null:null}var ud=/:\d+$/;function vd(a,b,c,d,e,f,g){g=void 0===g?!1:g;if(qd(a,b)){var h=b+"="+encodeURIComponent(c)+";";if(d){var k=new Date;k.setTime(k.getTime()+6E4*d);h+="expires="+k.toUTCString()+";"}e&&(d=e.replace(ud,""),h+="domain="+d+";");try{a.document.cookie=h+("path="+(f||"/")),g||(td(a)[b]=c)}catch(l){}}}
var wd=y(function(a){var b=(U(a).host||"").split(".");return 1===b.length?b[0]:E(function(c,d,e){e+=1;2<=e&&!c&&(e=R(".",b.slice(-e)),vd(a,"metrika_enabled","1",0,e,void 0,!0),(d=(d=sd(a))&&d.metrika_enabled)&&vd(a,"metrika_enabled","",-100,e,void 0,!0),d&&(c=e));return c},"",b)});
function xd(a,b,c){b=void 0===b?"_ym_":b;c=void 0===c?"":c;var d=wd(a),e=1===(d||"").split(".").length?d:"."+d,f=c?"_"+c:"";return{va:function(g,h,k){vd(a,""+b+g+f,"",-100,h||e,k,!1);return this},m:function(g){return rd(a,""+b+g+f)},A:function(g,h,k,l,m){vd(a,""+b+g+f,h,k,l||e,m);return this}}}
var yd=y(xd),zd=y(function(a){var b=yd(a),c="1"===b.m("debug"),d=-1<La(U(a).href,"_ym_debug=1")||-1<La(U(a).href,"_ym_debug=2"),e=a._ym_debug;!e&&!d||c||(a=U(a),b.A("debug","1",void 0,a.host));return!!(c||e||d)});function Ad(){return{}}function Bd(){return[]}var Dd=cd("debuggerEvents",Bd,!0);function Ed(a,b){if(zd(a)){var c=b.counterKey;if(c){var d=p(c.split(":"));c=d.next().value;d=d.next().value;c=dd(Kb(c));if("1"===d||c)return}c=Dd(a);1E3===c.length&&c.shift();c.push(b)}}
function Fd(a,b,c){var d=bd(a),e=c.Y,f=c.K,g=c.ga,h=c.Ea;c=c.hb;var k={},l={},m={};Ed(a,(m.name="request",m.data=(l.url=b,l.requestId=d,l.senderParams=(k.rBody=f,k.debugStack=e,k.rHeaders=g,k.rQuery=h,k.verb=c,k),l),m));return d}function Gd(a,b){return Array.prototype.find.call(b,a)}
var Hd=t(function(a,b){var c=b||{};return{l:C(c,x),m:function(d,e){var f=c[d];return Pa(f)&&!Pa(e)?e:f},A:function(d,e){c[d]=e;return this},ab:function(d,e){return""===e||Qa(e)?this:this.A(d,e)},Ha:C(c,a)}}),Id=Hd(function(a){var b="";a=E(function(c,d){var e=p(d),f=e.next().value;e=e.next().value;e=""+f+":"+e;"t"===f?b=e:c.push(e);return c},[],Rb(a));b&&a.push(b);return R(":",a)});
function Jd(a,b,c){var d=M({},b.B);a=T(a);b.D&&(d["browser-info"]=Id(b.D.l()).A("st",a(Mc)).Ha());!d.t&&(b=b.X)&&(b.A("ti",c),d.t=b.Ha());return d}
function Kd(a,b,c,d,e,f){e=void 0===e?0:e;f=void 0===f?0:f;var g=M({Y:[]},d.I),h=p(b[f]),k=h.next().value;h=h.next().value;var l=c[e];if((!g.ga||!g.ga["Content-Type"])&&g.K){var m={};g.ga=M({},g.ga,(m["Content-Type"]="application/x-www-form-urlencoded",m));g.K="site-info="+Yc(g.K)}g.hb=g.K?"POST":"GET";g.Ea=Jd(a,d,k);g.T=(d.$||{}).T;g.Y.push(k);M(d.I,g);k=""+l+(d.Da&&d.Da.vc?"/1":"");var n=0;n=Fd(a,k,g);return h(k,g).then(function(q){var r=n,v={},w={};Ed(a,(w.name="requestSuccess",w.data=(v.body=
q,v.requestId=r,v),w));return{zc:q,Pc:e}})["catch"](function(q){var r=n,v={},w={};Ed(a,(w.name="requestFail",w.data=(v.error=q,v.requestId=r,v),w));r=f+1>=b.length;v=e+1>=c.length;r&&v&&xc(q);return Kd(a,b,c,d,!v&&r?e+1:e,r?0:f+1)})}function Ld(a,b){return function(c,d){return Kd(a,b,d,c)}}function Md(a,b){J(F(x,Wa("push",a)),b);return a}function Nd(a,b){return b?a(b):a()}
var Od=F(x,Nd),Pd={id:"id",Qb:"ut",L:"type",Ta:"ldc",Aa:"nck",Na:"url",kc:"referrer"},Qd=/^\d+$/,Rd={id:function(a){a=""+(a||"0");Qd.test(a)||(a="0");try{var b=Nb(a)}catch(c){b=0}return b},L:function(a){return""+(a||0===a?a:"0")},Aa:kb,Qb:kb};Pd.Ja="defer";Rd.Ja=kb;Pd.G="params";Rd.G=function(a){return Ra(a)||tb(a)?a:null};Pd.Mb="trackLinks";var qc=E(function(a,b){var c=p(b),d=c.next().value;c=c.next().value;a[d]={V:c,Wa:Rd[d]};return a},{},Rb(Pd));
function Sd(a){return E(function(b,c){var d=p(c),e=d.next().value;d=d.next().value;b[qc[e].V]=d;return b},{},Rb(a))}function Td(a,b,c){for(var d=[b,c],e=-1E4,f=0;f<a.length;f+=1){var g=p(a[f]),h=g.next().value;g=g.next().value;if(c===g&&h===b)return;if(c<g&&c>=e){a.splice(f,0,d);return}e=g}a.push(d)}
var Ud={},Vd=(Ud.w=[[function(a,b){return{H:function(c,d){var e=c.B,f={};e=(f["page-url"]=e&&e["page-url"]||"",f.charset="utf-8",f);"0"!==b.L&&(e["cnt-class"]=b.L);c.D||(c.D=Id());f=c.D;e={$:{T:"watch/"+b.id},I:M(void 0===c.I?{}:c.I,{Rb:!!f.m("pv")&&!f.m("ar")&&!f.m("wh")}),B:M(c.B||{},e)};M(c,e);d()}}},1]],Ud);
function Wd(a,b,c){var d=Ld(a,b);return function(e){return Xc(c,e,!0).then(function(){var f=e.$||{},g=void 0===f.nc?"":f.nc,h=void 0===f.T?"":f.T;f=J(function(k){return N.ia+"//"+(""+g+k||lc)+"/"+h},void 0===f.qb?[lc]:f.qb);return d(e,f)}).then(function(f){var g=f.zc;f=f.Pc;e.cd=g;e.dd=f;return Xc(c,e).then(C(g,x))})}}function Xd(a){return function(b,c,d){return function(e,f){var g=J(F(wb,ab([b,f]),Nd),Vd[a]||[]);g=Md(g,d);return Wd(b,c,g)(e)}}}var Yd=Xd("w"),Zd=["webkitvisibilitychange","visibilitychange"];
function $d(a){return{H:function(b,c){var d=a.document,e=b.D;if(e&&gc(a)){var f=Fc(a),g=function(h){gc(a)||(f.ra(d,Zd,g),c());return h};f.C(d,Zd,g);e.A("pr","1")}else c()}}}function ae(a){var b="";tb(a)?b=R(".",a):Ha(a)&&(b=a);return vc("err.kn("+N.da+")"+b)}function be(){var a=Fa(arguments);xc(ae(a))}var ce=Xa(RegExp("^err.kn")),de=[];
function ee(a,b,c){var d="u.a.e",e="";c&&("object"===typeof c?(c.unk&&xc(c),d=c.message,e="string"===typeof c.stack&&c.stack.replace(/\n/g,"\\n")||"n.s.e.s"):d=""+c);ce(d)||Jb(C(d,Ma),sc)||wc(d)&&.1<=a.Math.random()||J(F(x,ab(["jserrs",d,b,e]),Nd),de)}function V(a,b,c,d){var e=c||xc;return function(){var f=d;try{f=e.apply(null,arguments)}catch(g){ee(a,b,g)}return f}}function W(a,b,c){return function(){return V(arguments[0],a,b,c).apply(this,arguments)}}
var fe=Hd(function(a){a=Rb(a);return R("",J(function(b){var c=p(b);b=c.next().value;c=c.next().value;return Oa(c)?"":b+"("+c+")"},a))});function ge(a,b,c){c=void 0===c?null:c;a.X||(a.X=fe());b&&a.X.ab(b,c);return a.X}
var he=[],ie=/^\s*(data|javascript):/i,je=new RegExp(R("",["\\.("+R("|","3gp 7z aac ac3 acs ai avi ape apk asf bmp bz2 cab cdr crc32 css csv cue divx dmg djvu? doc(x|m|b)? emf eps exe flac? flv iso swf gif t?gz jpe?g? js m3u8? m4a mp(3|4|e?g?) m4v md5 mkv mov msi ods og(g|m|v) psd rar rss rtf sea sfv sit sha1 svg tar tif?f torrent ts txt vob wave? wma wmv wmf webm ppt(x|m|b)? xls(x|m|b)? pdf phps png xpi g?zip".split(" "))+")$"]),"i"),X={},ke=(X.hit="h",X.params="p",X.reachGoal="g",X.userParams="up",
X.trackHash="th",X.accurateTrackBounce="atb",X.notBounce="nb",X.addFileExtension="fe",X.extLink="el",X.file="fc",X.trackLinks="tl",X.destruct="d",X.setUserID="ui",X.getClientID="ci",X.clickmap="cm",X.enableAll="ea",X),le={mc:function(a){a=rc(a).m("mt",{});a=Rb(a);return a.length?E(function(b,c,d){var e=p(c);c=e.next().value;e=e.next().value;return""+b+(d?"-":"")+c+"-"+e},"",a):null}};function me(a,b){if(!b)return null;try{return a.JSON.parse(b)}catch(c){return null}}
function ne(a,b){try{return a.JSON.stringify(b,null,void 0)}catch(c){return null}}function oe(a){try{return a.localStorage}catch(b){}return null}function pe(a,b){var c=oe(a);try{c.removeItem(b)}catch(d){}}function qe(a,b){var c=oe(a);try{return me(a,c.getItem(b))}catch(d){}return null}function re(a,b,c){var d=oe(a);a=ne(a,c);if(!Oa(a))try{d.setItem(b,a)}catch(e){}}var se=y(function(a){re(a,"_ymBRC","1");var b="1"!==qe(a,"_ymBRC");b||pe(a,"_ymBRC");return b});
function te(a,b,c){var d=""+(void 0===c?"_ym":c)+(void 0===b?"":b);d&&(d+="_");return{pc:se(a),m:function(e,f){var g=qe(a,""+d+e);return Oa(g)&&!Pa(f)?f:g},A:function(e,f){re(a,""+d+e,f);return this},va:function(e){pe(a,""+d+e);return this}}}var ue=y(te),ve=y(te,function(a,b,c){return""+b+c});function we(a){if(Qa(a))return!1;a=a.nodeType;return 3===a||8===a}function xe(a){return a?a.innerText||"":""}
var ye=y(function(a){a=G(a,"document")||{};return(""+(a.characterSet||a.charset||"")).toLowerCase()}),ze=y(F(H("document"),C("createElement",gb)));function Ae(a){var b=a&&a.parentNode;b&&b.removeChild(a)}function Be(a,b){try{return(new RegExp("(?:^|\\s)"+a+"(?:\\s|$)")).test(b.className)}catch(c){return!1}}
var Ce=y(function(a){var b=G(a,"Element.prototype");return b?(a=Gd(function(c){var d=b[c];return!!d&&ua(c,d)},["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"]))?b[a]:null:null});function De(a){a=G(a,"document");try{return a.getElementsByTagName("body")[0]}catch(b){return null}}function Ee(a){var b=G(a,"document")||{},c=b.documentElement;return"CSS1Compat"===b.compatMode?c:De(a)||c}
function Fe(a){var b=G(a,"visualViewport.width"),c=G(a,"visualViewport.height");a=G(a,"visualViewport.scale");return Qa(b)||Qa(c)?null:[Math.floor(b),Math.floor(c),a]}function Ge(a){var b=Fe(a);if(b){var c=p(b);b=c.next().value;var d=c.next().value;c=c.next().value;return[a.Math.round(b*c),a.Math.round(d*c)]}b=Ee(a);return[G(b,"clientWidth")||a.innerWidth,G(b,"clientHeight")||a.innerHeight]}
function He(a){try{return a.getBoundingClientRect&&a.getBoundingClientRect()}catch(b){return a=b,"object"===typeof a&&null!==a&&16389===(a.wc&&a.wc&65535)?{top:0,bottom:0,left:0,width:0,height:0,right:0}:null}}var Ie=/\/$/;function Je(a){var b=P(a),c=b.m("hitId");c||(c=bd(a),b.A("hitId",c));return c}function Ke(a,b){var c=ue(a),d=yd(a),e=b.Ta||"uid";return[c.m(e),d.m(e)]}var Le=cd("r",function(a,b){var c=p(Ke(a,b)),d=c.next().value;return!c.next().value&&d});
function Me(a,b){var c=b.Ta,d=c||"uid";c=c?a.location.hostname:void 0;var e=yd(a),f=ue(a),g=T(a)(Mc),h=p(Ke(a,b)),k=h.next().value;h=h.next().value;var l=e.m("d");Le(a,b);var m=!1;!h&&k&&(h=k,m=!0);if(!h)h=R("",[g,bd(a,1E6,999999999)]),m=!0;else if(!l||15768E3<g-Nb(l))m=!0;m&&!b.Aa&&(e.A(d,h,525600,c),e.A("d",""+g,525600,c));f.A(d,h);return h}function Ne(a,b,c){return gb("setTimeout",a)(b,c)}function Oe(a,b){return gb("clearTimeout",a)(b)}
function Pe(a,b,c,d){return Ne(a,V(a,"d.err."+(d||"def"),b),c)}function Qe(a,b){return function(c){return c(a,b)}}function Re(a){return ra(function(b,c){c(a)})}function Se(a){function b(e){G(c,d)?e():Pe(a,C(e,b),100)}var c=void 0===c?a:c;var d=(c.nodeType?"contentWindow.":"")+"document.body";return ra(function(e,f){b(f)})}function Te(a){var b=[],c={ad:b};c.C=F(Wa("push",b),C(c,x));c.Ca=F(oa(ya(a))(b),oa(Wa("splice",b))(1),C(c,x));c.N=F(x,oa(Nd),Gb(b));return c}
function Ue(a){var b={};return{C:function(c,d){J(function(e){G(b,e)||(b[e]=Te(a));b[e].C(d)},c);return this},Ca:function(c,d){J(function(e){G(b,e)&&b[e].Ca(d)},c);return this},N:function(c,d){return G(b,c)?V(a,"e."+c,b[c].N,[])(d):[]}}}var Ve=y(function(){return{W:{},pending:{},children:{}}}),We=H("postMessage");
function Xe(a,b){return function(c,d){var e={Ka:T(a)(S),key:a.Math.random(),dir:0};c.length&&(e.Ka=Nb(c[0]),e.key=parseFloat(c[1]),e.dir=Nb(c[2]));M(d,b);var f={};f=(f.data=d,f.__yminfo=R(":",["__yminfo",e.Ka,e.key,e.dir]),f);return{meta:e,Lb:ne(a,f)||""}}}var Ye=W("s.f",function(a,b,c,d,e){b=b(d);var f=Ve(a),g=R(":",[b.meta.Ka,b.meta.key]);if(We(c)){f.pending[g]=e;try{c.postMessage(b.Lb,"*")}catch(h){delete f.pending[g];return}Pe(a,function(){delete f.pending[g]},5E3,"if.s")}});
function Ze(a){if(ua("MutationObserver",a.MutationObserver)){var b=Ve(a).children,c=new a.MutationObserver(function(){J(function(d){G(b[d],"window.window")||delete b[d]},L(b))});Se(a)(Qe(u,function(){c.observe(a.document.body,{subtree:!0,childList:!0})}))}}
function $e(a,b){var c=Ve(a);b.C(["initToParent"],function(d){var e=p(d);d=e.next().value;e=e.next().value;window.window&&(c.children[e.counterId]={info:e,window:d.source})}).C(["initToChild"],function(d){var e=p(d);d=e.next().value;e=e.next().value;d.source===a.parent&&b.N("parentConnect",[d,e])}).C(["parentConnect"],function(d){var e=p(d);d=e.next().value;e=e.next().value;e.counterId&&(c.W[e.counterId]={info:e,window:d.source})})}
var af=W("s.fh",function(a,b,c,d,e,f){var g=null,h=null,k=Ve(a),l=null;try{g=me(a,f.data),h=g.__yminfo,l=g.data}catch(m){return}if(!Qa(h)&&h.substring&&"__yminfo"===h.substring(0,8)&&!Qa(l)&&(a=h.split(":"),4===a.length))if(g=b.id,h=p(a),h.next(),b=h.next().value,a=h.next().value,h=h.next().value,!tb(l)&&l.type&&"0"===h&&l.counterId){if(!l.toCounter||l.toCounter==g){k=null;try{k=f.source}catch(m){}!Oa(k)&&We(k)&&(f=d.N(l.type,[f,l]),e=J(F(x,Sb(e)),f.concat([void 0])),l=c([b,a,l.counterId],e),k.postMessage(l.Lb,
"*"))}}else h===""+g&&tb(l)&&nb(function(m){return!(!m.hid||!m.counterId)},l).length===l.length&&(c=k.pending[R(":",[b,a])])&&c.apply(null,[f].concat(l))}),bf=y(function(a,b){var c=gb("getElementsByTagName",G(a,"document")),d=Ve(a),e=We(a),f=Ue(a),g=Fc(a);if(!c||!e)return null;c=c.call(a.document,"iframe");e={};e=(e.counterId=b.id,e.hid=""+Je(a),e);jc(a)&&(e.duid=Me(a,b));$e(a,f);Ze(a);var h=Xe(a,e),k=A([a,C([],h)],Ye);J(function(l){var m=null;try{m=l.contentWindow}catch(n){}m&&k(m,{type:"initToChild"},
function(n,q){f.N("initToParent",[n,q])})},c);dc(a)&&k(a.parent,{type:"initToParent"},function(l,m){f.N("parentConnect",[l,m])});g.C(a,["message"],A([a,b,h,f,e],af));return{aa:f,W:d.W,children:d.children,Gb:k}},F(Ba,O)),cf=y(function(a,b){if(!jc(a)||!dc(a))return Me(a,b);var c=bf(a,b);return c&&c.W[b.id]?c.W[b.id].info.duid||Me(a,b):Me(a,b)},function(a,b){return""+b.Ta+b.Aa}),df=y(F(T,ra(function(a){return-(new a.l.Date).getTimezoneOffset()}))),ef=F(T,ra(function(a){a=new a.l.Date;return R("",J(Jc,
[a.getFullYear(),a.getMonth()+1,a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds()]))})),ff=F(T,ra(Mc)),gf=y(F(T,ra(function(a){return p(a.S).next().value}))),hf=y(function(a){a=P(a);var b=a.m("counterNum",0)+1;a.A("counterNum",b);return b},F(Ba,O)),Y={},jf=(Y.vf=C(la.version,x),Y.nt=$b,Y.fu=function(a,b,c){var d=c.B;if(!d)return null;b=(G(a,"document.referrer")||"").replace(Ie,"");c=(d["page-ref"]||"").replace(Ie,"");d=d["page-url"];a=U(a).href!==d;b=b!==c;c=0;a&&b?c=3:b?c=1:a&&(c=2);return c},
Y.en=ye,Y.la=bc,Y.ut=function(a,b,c){var d=c.F;c=c.B;d=d&&d.Ba;c&&(jd(a)||b.Qb||d)&&(c.ut=N.Yb);return null},Y.v=C(N.da,x),Y.cn=hf,Y.dp=function(a){var b=P(a),c=b.m("bt",{});if(Pa(b.m("bt"))){var d=G(a,"navigator.getBattery");try{c.p=d&&d.call(a.navigator)}catch(e){}b.A("bt",c);c.p&&c.p.then&&c.p.then(V(a,"bi:dp.p",function(e){c.Qc=G(e,"charging")&&0===G(e,"chargingTime")}))}return jb(c.Qc)},Y.ls=y(function(a,b){var c=ve(a,b.id),d=T(a),e=c.m("lsid");return+e?e:(d=bd(a,0,d(S)),c.A("lsid",d),d)},Ba),
Y.hid=Je,Y.phid=function(a,b){if(!dc(a))return null;var c=bf(a,b);if(!c)return null;var d=L(c.W);return d.length?c.W[d[0]].info.hid:null},Y.z=df,Y.i=ef,Y.et=ff,Y.c=F(H("navigator.cookieEnabled"),ib),Y.rn=F(x,bd),Y.rqn=function(a,b,c){c=c.B;if(!c||c.nohit)return null;b=O(b);a=ve(a,b);b=(a.m("reqNum",0)||0)+1;a.A("reqNum",b);if(a.m("reqNum")===b)return b;a.va("reqNum");return null},Y.u=cf,Y.w=function(a){var b=p(Ge(a));a=b.next().value;b=b.next().value;return a+"x"+b},Y.s=function(a){var b=G(a,"screen");
if(b){a=G(b,"width");var c=G(b,"height");b=G(b,"colorDepth")||G(b,"pixelDepth");return R("x",[a,c,b])}return null},Y.sk=H("devicePixelRatio"),Y.ifr=F(dc,ib),Y.j=F(fc,ib),Y.sti=function(a){return dc(a)&&ec(a)?"1":null},Y),kf=y(function(){return Md(L(jf),L(le))});function lf(a){return function(b,c){return{H:function(d,e){var f=d.D,g=d.B;f&&g&&J(function(h){var k=jf[h],l="bi",m=f;k||(k=le[h],l="tel",m=ge(d));k&&(k=W(l+":"+h,k,null)(b,c,d),m.ab(h,k))},a||kf());e()}}}}
function mf(a){return{H:function(b,c){var d=b.D;if(d){var e=a.document.title;b.F&&b.F.title&&(e=b.F.title);var f=gb("getElementsByTagName",a.document);"string"!==typeof e&&f&&(e=f("title"),e=(e=G(e,"0.innerHtml"))?e:"");e=e.slice(0,N.Vb);d.A("t",e)}c()}}}var nf=y(Ad,O);function of(a,b,c){if(jc(a)&&dc(a)){var d=nf(b);if(!d.qc){d.qc=!0;b=bf(a,b);if(!b){c();return}d.P=[];var e=function(){d.P&&(J(Nd,d.P),d.P=null)};Pe(a,e,3E3);b.aa.C(["initToChild"],e)}d.P?d.P.push(c):c()}else c()}
var pf=y(function(){return{pb:null,P:[]}},O);function qf(a){return(a=a.D)&&a.m("pv")&&!a.m("ar")}function rf(a,b,c){var d=a.D;d?qf(a)?(b.pb=d,c()):b.P?b.P.push(c):c():c()}function sf(a,b){return{H:function(c,d){var e=pf(b);e=A([c,e,d],rf);of(a,b,e)},ca:function(c,d){var e=c.D,f=pf(b);if(e){var g=f.P;f.pb===e&&g&&(J(Nd,g),f.P=null)}d()}}}var tf=/^[a-z][\w.+-]+:/i;
function uf(a,b){var c=U(a),d=c.href,e=c.host,f=-1;if(!Ha(b)||Pa(b))return d;c=b.replace(kd,"");if(-1!==c.search(tf))return c;var g=c.charAt(0);if("?"===g&&(f=d.search(/\?/),-1===f)||"#"===g&&(f=d.search(/#/),-1===f))return d+c;if(-1!==f)return d.substr(0,f)+c;if("/"===g){if(f=Ka(d,e),-1!==f)return d.substr(0,f+e.length)+c}else return d=d.split("/"),d[d.length-1]=c,R("/",d);return""}
function vf(a){return{H:function(b,c){var d=b.B;if(!b.D||!d)return c();var e=d["page-ref"],f=d["page-url"];e&&f!==e?d["page-ref"]=uf(a,e):delete d["page-ref"];d["page-url"]=uf(a,f).slice(0,N.Wb);return c()}}}var wf=[[$d,1],[sf,2],[lf(),3],[mf,4]],xf=[],yf=C(wf,Td),zf={},Af=(zf.h=wf,zf),Z=C(Af,function(a,b,c,d){a[b]||(a[b]=[]);c&&!Qa(d)&&Td(a[b],c,d)});yf(vf,-100);function Bf(a,b,c){b=tb(b)?b:Af[b]||wf;var d=J(wb,b);J(function(e){return d.unshift(e)},xf);return J(F(ab([a,c]),Nd),d)}
function Cf(a,b){var c=ze(a);if(c){var d=a.document,e=c("script");e.src=b.src;e.type=b.type||"text/javascript";e.charset=b.charset||"utf-8";e.async=b.async||!0;try{var f=d.getElementsByTagName("head")[0];if(!f){var g=d.getElementsByTagName("html")[0];f=c("head");g&&g.appendChild(f)}f.insertBefore(e,f.firstChild);return e}catch(h){}}}var Df=y(function(a){if(a=ze(a))return a("a")});
function Ef(a,b){var c=Df(a);return c?(c.href=b,{protocol:c.protocol,host:c.host,port:c.port,hostname:c.hostname,hash:c.hash,search:c.search,query:c.search.replace(/^\?/,""),pathname:c.pathname||"/",path:(c.pathname||"/")+c.search,href:c.href}):{}}function Ff(a){return(a.split(":")[1]||"").replace(/^\/*/,"").replace(/^www\./,"").split("/")[0]}function Gf(a,b){if(!b||!b.length)return a;var c=p(a.split("#")),d=c.next().value;c=ca(c);c=(c=R("#",c))?"#"+c:"";return Ma(a,"?")?d+"&"+b+c:d+"?"+b+c}
var Hf=/[^a-z0-9.:-]/;function If(a,b,c,d,e,f,g,h){if(4===b.readyState)if(200===b.status||e||g(c),e)200===b.status?f(b.responseText):g(vc("http."+b.status+".st."+b.statusText+".rt."+(""+b.responseText).substring(0,50)));else{e=null;if(d)try{(e=me(a,b.responseText))||g(c)}catch(k){g(c)}f(e)}return h}
function Jf(a,b,c){var d=new a.XMLHttpRequest,e=c.K,f={},g=M(c.Rb?(f.wmode="7",f):{},c.Ea);return new Q(function(h,k){d.open(c.hb||"GET",Gf(b,ad(g)),!0);d.withCredentials=!1!==c.hd;c.cb&&(d.timeout=c.cb);F(Rb,Fb(function(m){var n=p(m);m=n.next().value;n=n.next().value;d.setRequestHeader(m,n)}))(c.ga);var l=A([a,d,ae(c.Y),c.Rb,c.ed,h,k],If);d.onreadystatechange=l;try{d.send(e)}catch(m){}})}
function Lf(a,b,c,d){return new Q(function(e,f){var g=Ee(a),h=b("img"),k=F(C(h,Ae),C(ae(d.Y),f)),l=Ne(a,k,d.cb||3E3);h.onerror=k;h.onload=F(C(h,Ae),C(null,e),A([a,l],Oe));l=M({},d.Ea);delete l.wmode;k=c;(l=ad(l))&&(k=Gf(k,l));d.K&&(k=Gf(k,d.K));h.src=k;Vb(a)&&(M(h.style,{position:"absolute",visibility:"hidden",width:"0px",height:"0px"}),g.appendChild(h))})}
var Mf={},Nf=(Mf.x={id:2,check:function(a){var b;if(b=G(a,"XMLHttpRequest"))if(b="withCredentials"in new a.XMLHttpRequest){a:{if(Hf.test(a.location.host)&&a.opera&&z(a.opera.version)&&(b=a.opera.version(),"string"===typeof b&&"12"===b.split(".")[0])){b=!0;break a}b=!1}b=!b}return b?C(a,Jf):!1}},Mf.i={id:4,check:function(a){var b=ze(a);return b?A([a,b],Lf):!1}},Mf),Of={};function Pf(a){if(a)return E(function(b,c){var d=Nf[c];d&&b.push(d);return b},[],a)}
function Qf(a){return Of["*"]?Pf(Of["*"]):a?Pf(Of[a]):void 0}
var Rf=["b","f","x","j","i"],Sf=["x"],Tf=["i"],Uf={},Vf=(Uf.h=Sf,Uf),Wf=y(function(a,b,c){(c=Qf(b)||Pf(c))||(c=Pf(b?Vf[b]:Rf));b=E(function(d,e){var f=e.check,g=e.id;(f=f(a))&&d.push([g,f]);return d},[],c||[]);b.length||be();return b},Ba),Xf=Va(Q.reject,Q,ae()),Yf={},Zf=(Yf.h=Yd,Yf),$f=W("g.sen",function(a,b,c){var d=Wf(a,b);c=c?Bf(a,b,c):[];var e=Zf[b],f=e?e(a,d,c):Yd(a,d,c);return function(){var g=p(Fa(arguments)),h=g.next().value;g=ca(g);h=M(h,{I:M(void 0===h.I?{}:h.I,{Y:[b]})});return f.apply(null,
[h].concat(g))}},Xf);function ag(a,b){return function(c){var d=c[a];d?(d.Db=!0,d.Cb(b)):c[a]={promise:Q.resolve(b),Db:!0,Cb:u}}}var bg=t(function(a,b){if(!b[a]){var c,d=new Q(function(e){c=e});b[a]={Cb:c,promise:d,Db:!1}}return b[a].promise}),cg=y(F(Ad,ra));function dg(a,b,c){b=O(b);var d=Kc(a);c=M({ic:d(S)},c);d={};var e={};Ed(a,(e.counterKey=b,e.name="counterSettings",e.data=(d.settings=c,d),e));return cg()(ag(b,c))}function eg(a,b){var c=O(a);return cg()(bg(c)).then(b)}
function fg(a,b){function c(d,e,f){var g={},h={};Ed(a,(h.name="log",h.counterKey=b,h.data=(g.args=tb(e)?e:[e],g.type=d,g.variables=f,g),h))}return{log:C("log",c),error:C("error",c),warn:C("warn",c)}}var gg=y(W("dc.init",function(a,b){return b&&dd(Kb(b.split(":")[0]))?{log:u,warn:u,error:u}:fg(a,b)}),Ba);function hg(a,b,c,d){gg(a,b).log(c,d)}function ig(a,b,c,d,e){return A([a,O(b),e?[c+".p",e]:c,d],hg)}
function jg(a,b){if(a.postMessage&&!a.attachEvent){var c=Fc(a),d="__ym__promise_"+bd(a)+"_"+bd(a),e=u;e=c.C(a,["message"],V(a,"as",function(f){try{var g=f.data}catch(h){return}g===d&&(e(),f.stopPropagation&&f.stopPropagation(),b())}));a.postMessage(d,"*")}else Pe(a,b,0,"as")}
var kg=W("h.p",function(a,b){var c=$f(a,"h",b),d=b.Na||""+U(a).href,e=b.kc||a.document.referrer,f={},g={};f={D:Id((f.pv=1,f)),B:(g["page-url"]=d,g["page-ref"]=e,g),F:{}};f.F.G=b.G;b.Ja&&f.B&&(f.B.nohit="1");return c(f,b).then(function(h){if(h){if(!b.Ja){var k={};ig(a,b,"h",(k.id=b.id,k.url=d,k.ref=e,k),b.G)()}jg(a,A([a,b,h],dg))}})["catch"](V(a,"h.g.s"))});
function lg(a,b,c){try{if(z(b)){var d=p(Fa(arguments));d.next();d.next();d.next();var e=ca(d);b.apply(Qa(c)?null:c,e)}}catch(f){Ne(a,C(f,xc),0)}}var mg=["yandex_metrika_callback"+la.callbackPostfix,"yandex_metrika_callbacks"+la.callbackPostfix],ng=W("cb.i",function(a){var b=p(mg),c=b.next().value,d=b.next().value;if(z(a[c]))a[c]();"object"===typeof a[d]&&J(function(e,f){a[d][f]=null;lg(a,e)},a[d]);J(function(e){try{delete a[e]}catch(f){a[e]=void 0}},mg)});
function og(a,b){var c=P(a).m("counters",{}),d=O(b);return c[d]}function pg(a,b,c,d){var e=ke[c];return e?function(){var f=Fa(arguments);f=d.apply(null,da(f));var g=P(a);g.O("mt",{});g=g.m("mt");var h=g[e];g[e]=h?h+1:1;return f}:d}var qg=[],rg=[],sg=[],tg=[],ug=[],vg=[],wg=F(La,pa(0)),xg=oa(wg);function yg(a){a=P(a);var b=a.m("dsjf")||ra({});a.O("dsjf",b);return b}function zg(a,b,c){yg(a)(function(d){d[b]=M(d[b]||{},c)})}function Ag(a,b){yg(a)(function(c){delete c[b]})}
function Bg(a,b){return function(c){zg(a,b,c)}}var Cg=t(function(a,b){var c={};yg(a)(function(d){c=d[b]||{}});return c}),Dg=W("c.c.cc",function(a){var b=P(a),c=F(Cg(a),function(d){var e={};e=(e.clickmap=!!d.clickmap,e);return M({},d,e)});return V(a,"g.c.cc",F(Va(b.m,b,"counters",{}),L,Fb(c)))}),Eg=W("gt.c.rs",function(a,b){var c=O(b),d=b.id,e=b.L,f=b.Wc,g=b.gd,h=A([a,c],Ag),k={};zg(a,c,(k.id=d,k.type=+e,k.clickmap=f,k.trackHash=!!g,k));return h}),Fg={};
function Gg(a,b){var c=O(a),d=G(b,"__ym.turbo_page"),e=G(b,"__ym.turbo_page_id");Fg[c]||(Fg[c]={});if(d||e)Fg[c].Kc=d,Fg[c].Lc=e}function Hg(a){a=O(a);return Fg[a]&&Fg[a].Kc}var Ig=y(Bd);
function Jg(a,b){return{H:function(c,d){var e=(c.F||{}).G,f=void 0===c.I?{}:c.I;if(e&&(Gg(b,e),!f.K&&c.D&&c.B)){var g=ne(a,e),h=Ig(a),k=c.D.m("pv");if(g&&!c.B.nohit){var l={},m={};Ed(a,(m.counterKey=O(b),m.name="params",m.data=(l.val=e,l),m));k?encodeURIComponent(g).length>N.Ub?h.push([c.D,e]):c.B["site-info"]=g:(f.K=g,c.I=f,c.Da||(c.Da={}),c.Da.vc=!0)}}d()},ca:function(c,d){var e=Ig(a),f=og(a,b),g=f&&f.params;g&&(f=nb(F(wb,pa(c.D)),e),J(function(h){var k=p(h);k.next();k=k.next().value;g(k);h=vb(a)(h,
e);e.splice(h,1)},f));d()}}}function Kg(a,b,c,d,e){var f=A([a,d,e],lg);return c.then(f,function(g){f();ee(a,b,g)})}var Lg=y(Ad,O);function Mg(a){var b=u,c=null,d=a.length;if(0!==a.length&&a[0]){var e=a.slice(-1)[0];z(e)&&(b=e,d=a.length+-1);var f=a.slice(-2)[0];z(f)&&(b=f,c=e,d=a.length+-2);d=a.slice(0,d);return{fc:c,ta:b,G:1===d.length?a[0]:fb(d)}}}
var Ng=W("pa.int",function(a,b){var c={};return c.params=function(){var d=Fa(arguments),e=Mg(d);if(!e)return null;d=e.fc;var f=e.G;e=e.ta;if(!Ra(f)&&!tb(f))return null;var g=$f(a,"1",b),h=Lg(b).url,k=!ed(b),l={};l=(l.id=b.id,l);var m=f;m.__ym&&(m=M({},f),m.__ym=E(function(q,r){var v=G(f,"__ym."+r);v&&(q[r]=v);return q},{},he),L(m.__ym).length||delete m.__ym,k=!!L(m).length);m=JSON.stringify(m);l=ig(a,b,"pa",l,m);m={};var n={};g=g({F:{G:f},D:Id((m.pa=1,m.ar=1,m)),B:(n["page-url"]=h||U(a).href,n)},
b).then(k?l:u);return Kg(a,"p.s",g,e,d)},c});function Og(a,b,c,d,e){return(new Q(function(f,g){var h=L(c),k=F(d.resolve||x,qa(f)),l=F(d.reject||x,qa(g));d.resolve=k;d.reject=l;J(function(m){d.eb.push(+m);var n=c[m],q=Pe(a,C(ae(),l),5100,"is.m"),r={};b(n.window,M(e,(r.toCounter=Nb(m),r)),function(v,w){Oe(a,q);d.Jb.push(m);d.resolve&&d.resolve(w)})},h)}))["catch"](V(a,"if.b"))}
function Pg(a,b,c){b=nb(function(d){return!I(c.info.counterId,d.eb)},b);J(function(d){if(c.info.counterId){var e={};a((e[c.info.counterId]=c,e),d,d.data)}},b)}
function Qg(a,b){var c=bf(a,b),d=[],e=[];if(!c)return null;var f=A([a,c.Gb],Og),g=C(f,Pg);c.aa.C(["initToParent"],function(h){h=p(h);h.next();h=h.next().value;g(d,c.children[h.counterId])}).C(["parentConnect"],function(h){h=p(h);h.next();h=h.next().value;g(e,c.W[h.counterId])});return{aa:c.aa,fd:function(h,k){return new Q(function(l,m){c.Gb(h,k,function(n,q){l([n,q])});Pe(a,C(ae(),m),5100,"is.o")})},Fb:function(h){var k={Jb:[],eb:[],data:h};d.push(k);return f(c.children,k,h)},Hb:function(h){var k=
{Jb:[],eb:[],data:h};e.push(k);return f(c.W,k,h)}}}var Rg=y(Qg,F(Ba,O));function Sg(a,b){if(!I(b,J(H("ymetrikaEvent.type"),a))){var c={},d={};a.push((d.ymetrikaEvent=(c.type=b,c),d))}}function Tg(a){a=P(a);var b=a.m("dataLayer",[]);a.A("dataLayer",b);return b}
function Ug(a,b,c){c=void 0===c?u:c;var d=void 0===d?!1:d;var e=Te(a);if(b&&z(b.push)){var f=b.push;b.push=function(){var g=Fa(arguments),h=p(g).next().value;d&&e.N(h);g=f.apply(b,g);d||e.N(h);return g};a={Xa:e,unsubscribe:function(){b.push=f}};c(a);J(e.N,b);return a}}function Vg(a,b){var c=G(b,"ymetrikaEvent");c&&a.N(G(c,"type"),c)}function Wg(a,b,c){c=void 0===c?x:c;var d=Ue(a);c(d);var e=C(d,Vg);Ug(a,b,function(f){f.Xa.C(e)});return d}
function Xg(a,b,c,d){var e=og(a,c);if(e){a=d.data;c=""+c.id;var f=d.sended||[];d.sended||(d.sended=f);I(c,f)||!e.params||d.counter&&""+d.counter!==c||(e.params(a),f.push(c),d.parent&&(d={},b.Hb((d.type="params",d.data=a,d))))}}var Yg=W("y.p",function(a,b){var c=Qg(a,b);if(c){var d=Tg(a),e=A([a,c,b],Xg);Wg(a,d,function(f){f.C(["params"],e)});c.aa.C(["params"],F(H("1"),e))}});
function Zg(a,b,c,d){var e=U(a),f=e.hostname;e=e.href;if(b=Lg(b).url)a=Ef(a,b),f=a.hostname,e=a.href;return[d+"://"+f+"/"+c,e||""]}
var $g={Zc:Xa(/[/&=?#]/)},ah=W("go.in",function(a,b,c,d){c=void 0===c?"goal":c;var e={};return e.reachGoal=function(f,g,h,k){if(!f||$g[c]&&$g[c](f))return null;var l=g,m=h||u;z(g)&&(m=g,l=void 0,k=h);g={};var n=ig(a,b,"gr",(g.id=b.id,g.goal=f,g),l),q="goal"===c;g=$f(a,"g",b);var r=p(Zg(a,b,f,c));h=r.next().value;r=r.next().value;var v={},w={};g=g({F:{G:l},D:Id((v.ar=1,v)),B:(w["page-url"]=h,w["page-ref"]=r,w)},b).then(function(){q&&n();var D={},B={};Ed(a,(B.counterKey=O(b),B.name="event",B.data=(D.schema=
c,D.name=f,D.params=l,D),B));d&&d()});return Kg(a,"g.s",g,m,k)},e});function bh(a){var b=null;try{b=a.target||a.srcElement}catch(c){}if(b){3===b.nodeType&&(b=b.parentNode);for(a=b&&b.nodeName&&(""+b.nodeName).toLowerCase();G(b,"parentNode.nodeName")&&("a"!==a&&"area"!==a||!b.href&&!b.getAttribute("xlink:href"));)a=(b=b.parentNode)&&b.nodeName&&(""+b.nodeName).toLowerCase();return b.href?b:null}return null}
function ch(a,b){var c={};c=(c.string=!0,c.object=!0,c["boolean"]=b,c)[typeof b]||!1;var d={};a((d.trackLinks=c,d))}
function dh(a,b,c){var d=Id();void 0!==c.ya&&d.A("ite",jb(c.ya));c.wa&&d.A("dl",1);c.fa&&d.A("ln",1);var e=c.Pb||{},f={};d={D:d,F:{title:e.title||c.title,Ba:!!c.Ba,G:e.params},B:(f["page-url"]=c.url,f["page-ref"]=b.Na||U(a).href,f)};f="Link";c.wa?f=c.fa?"Ext link - File":"File":c.fa&&(f="Ext link");var g={},h={};Ed(a,(h.counterKey=O(b),h.name="event",h.data=(g.schema="Link click",g.name=(c.fa?"external":"internal")+" url: "+c.url,g),h));g={};b=c.sender(d,b).then(ig(a,b,"lcl",(g.prefix=f,g.id=b.id,
g.url=c.url,g),c.Pb));Kg(a,"cl.p.s",b,e.callback||u,e.ctx)}
function eh(a,b){if(a.Mc()){var c=bh(b);if(c&&!Be("ym-disable-tracklink",c)){var d=a.l,e=a.dc,f=a.ec,g=a.sender,h=a.hc,k=f.Na,l=c.href;var m=md(c.innerHTML&&c.innerHTML.replace(/<\/?[^>]+>/gi,""));m||(m=(m=c.querySelector("img"))?md(m.getAttribute("title")||m.getAttribute("alt")):"");m=l===m?"":m;var n=G(b,"isTrusted");if(Be("ym-external-link",c))dh(d,f,{url:l,fa:!0,title:m,ya:n,sender:g});else{k=k?Ef(d,k).hostname:U(d).hostname;h=RegExp("\\.("+R("|",J(Na,h))+")$","i");var q=c.protocol+"//"+c.hostname+
c.pathname;h=je.test(q)||je.test(l)||h.test(l)||h.test(q);c=c.hostname;id(k)===id(c)?h?dh(d,f,{url:l,wa:!0,ya:n,title:m,sender:g}):m&&e.A("il",md(m).slice(0,100)):l&&ie.test(l)||dh(d,f,{url:l,Ba:!0,fa:!0,wa:h,ya:n,title:m,sender:g})}}}}
var fh=t(function(a,b){Ha(b)?a.push(b):J(F(x,Wa("push",a)),b)}),gh=cd("retryReqs",function(a){var b=ue(a),c=b.m("retryReqs",{}),d=T(a)(S);J(function(e){var f=p(e);e=f.next().value;f=f.next().value;(!f||!f.time||f.time+864E5<d)&&delete c[e]},Rb(c));b.A("retryReqs",c);return c},!0);function hh(a){var b=gh(a);ue(a).A("retryReqs",b)}function ih(a,b){var c=gh(a);b.D&&!Oa(c)&&b.F&&(delete c[b.F.qa],hh(a))}
function jh(a,b){return{H:function(c,d){var e=c.D,f=c.X,g=c.B,h=void 0===c.I?{}:c.I;if(e&&g){var k=T(a);e.ab("rqnl",1);for(var l=gh(a),m=1;l[m];)m+=1;c.F||(c.F={});c.F.qa=m;var n={};l[m]=(n.protocol=N.ia,n.host=lc,n.resource=c.$.T,n.postParams=h.K,n.time=k(S),n.counterType=b.L,n.params=g,n.browserInfo=e.l(),n.counterId=b.id,n.ghid=Je(a),n);f&&(l[m].telemetry=f.l());hh(a)}d()},ca:function(c,d){ih(a,c);d()}}}
var kh=[xg("watch"),xg("clmap")],lh=W("g.r",function(a){var b=T(a),c=gh(a),d=b(S),e=Je(a);return E(function(f,g){var h=p(g),k=h.next().value;(h=h.next().value)&&Jb(ra(h.resource),kh)&&!h.d&&h.ghid&&h.ghid!==e&&h.time&&500<d-h.time&&h.time+864E5>d&&2>=h.browserInfo.rqnl&&(h.d=1,k={protocol:h.protocol,host:h.host,T:h.resource,xc:h.postParams,G:h.params,$b:h.browserInfo,Xc:h.ghid,time:h.time,qa:Nb(k),counterId:h.counterId,L:h.counterType},h.telemetry&&(k.X=h.telemetry),f.push(k));return f},[],Rb(c))});
function mh(a,b,c){function d(){r||(q=!0,v=!1,r=!0,f())}function e(){m=!0;k(!1);b()}function f(){Oe(a,l);if(m)k(!1);else{var K=Math.max(0,c-(v?w:w+n(S)-D));K?l=Pe(a,e,K,"u.t.d.c"):e()}}function g(){v=q=r=!0;w+=n(S)-D;D=n(S);f()}function h(){q||r||(w=0);D=n(S);q=r=!0;v=!1;f()}function k(K){K=K?B.C:B.ra;K(a,["blur"],g);K(a,["focus"],h);K(a.document,["click","mousemove","keydown","scroll"],d)}var l=0,m=!1;if(ac(a))return l=Pe(a,b,c,"u.t.d"),A([a,l],Oe);var n=T(a),q=!1,r=!1,v=!0,w=0,D=n(S),B=Fc(a);k(!0);
f();return function(){Oe(a,l);k(!1)}}
var nh=W("nb.p",function(a,b){function c(w){h()||(w="number"===typeof w?w:15E3,v=mh(a,d(!1),w),l())}function d(w){return function(D){var B={};D=void 0===D?(B.ctx={},B.callback=u,B):D;if(w||!q&&!g.pc){q=!0;l();v&&v();var K=m(S);B=(Nb(g.m("lastHit"))||0)<K-18E5;var Lb=.1>Math.random();g.A("lastHit",K);K={};K=Id((K.nb=1,K.cl=r,K.ar=1,K));var Cd=Lg(b),Kf={};K={B:(Kf["page-url"]=Cd.url||U(a).href,Kf),D:K,F:{force:w}};Cd=gg(a,O(b)).warn;!D.callback&&D.ctx&&Cd("nbnc");(B=w||B||Lb)||(B=a.location.href,Lb=
a.document.referrer,B=!(B&&Lb?Ff(B)===Ff(Lb):!B&&!Lb));if(B)return B=e(K,b),Kg(a,"l.o.l",B,D.callback,D.ctx)}return null}}var e=$f(a,"n",b),f=O(b),g=ve(a,b.id),h=C(C(f,Cg(a)),F(Nd,H("accurateTrackBounce"))),k={},l=C((k.accurateTrackBounce=!0,k),Bg(a,f)),m=T(a),n=m(S),q=!1,r=0,v;eg(b,function(w){r=w.ic-n});b.ib&&c(b.ib);f={};return f.notBounce=d(!0),f.u=v,f});function oh(a){return!(!ua("querySelectorAll",G(a,"Element.prototype.querySelectorAll"))||!a.document.querySelectorAll)}
function ph(a,b){if(!b||!b.querySelectorAll)return[];var c=b.querySelectorAll(a);return c?ub(c):[]}function qh(a,b){if(b.querySelector)return b.querySelector(a);var c=ph(a,b);return c&&c.length?c[0]:null}
function rh(a,b,c){if(!(b&&b.Element&&b.Element.prototype&&b.document&&c))return null;if(b.Element.prototype.closest&&ua("closest",b.Element.prototype.closest)&&c.closest)return c.closest(a);var d=Ce(b);if(d){for(b=c;b&&1===b.nodeType&&!d.call(b,a);)b=b.parentElement||b.parentNode;return b&&1===b.nodeType?b:null}if(oh(b)){for(a=ub((b.document||b.ownerDocument).querySelectorAll(a));c&&1===c.nodeType&&-1===ya(b)(c,a);)c=c.parentElement||c.parentNode;return c&&1===c.nodeType?c:null}return null}
function sh(a){a=""+a;for(var b=2166136261,c=a.length,d=0;d<c;d+=1)b^=a.charCodeAt(d),b+=(b<<1)+(b<<4)+(b<<7)+(b<<8)+(b<<24);return b>>>0}function th(a,b,c,d){return function(){if(og(a,b)){var e=Fa(arguments);return d.apply(null,da(e))}}}R(",",J(function(a){return'input[type="'+a+'"]'},["button","submit","reset","file"]));
var uh={},vh=(uh.transaction_id="id",uh.item_brand="brand",uh.index="position",uh.item_variant="variant",uh.value="revenue",uh.item_category="category",uh.item_list_name="list",uh),wh={},xh=(wh.item_id="id",wh.item_name="name",wh.promotion_name="coupon",wh),yh={},zh=(yh.promotion_name="name",yh),Ah={},Bh=(Ah.promotion_name="name",Ah.promotion_id="id",Ah.item_id="product_id",Ah.item_name="product_name",Ah),Ch="currencyCode add delete remove purchase checkout detail impressions click promoView promoClick".split(" "),
Dh={},Eh=(Dh.view_item={event:"detail",U:xh,Z:"products"},Dh.add_to_cart={event:"add",U:xh,Z:"products"},Dh.remove_from_cart={event:"remove",U:xh,Z:"products"},Dh.begin_checkout={event:"checkout",U:xh,Z:"products"},Dh.purchase={event:"purchase",U:xh,Z:"products"},Dh.view_item_list={event:"impressions",U:xh},Dh.select_item={event:"click",Z:"products",U:xh},Dh.view_promotion={event:"promoView",Z:"promotions",U:Bh},Dh.select_promotion={event:"promoClick",Z:"promotions",U:Bh},Dh);
function Fh(a,b){var c={};J(function(d){var e=a[d]||vh[d]||d;-1!==Ka(d,"item_category")?(e=vh.item_category,c[e]=c[e]?c[e]+("/"+b[d]):b[d]):c[e]=b[d]},L(b));return c}
function Gh(a,b){var c=Ha(a)?Eh[a]:a;if(c){var d=c.event,e=c.Z,f=void 0===c.lc?"items":c.lc,g=b.purchase||b,h=g[f];if(h){c=J(C(c.U,Fh),h);h={};var k={},l=(k[d]=e?(h[e]=c,h):c,k);c=L(g);e&&1<c.length&&(l[d].actionField=E(function(m,n){if(n===f)return m;if("currency"===n)return l.currencyCode=g.currency,m;m[zh[n]||vh[n]||n]=g[n];return m},{},c));return l}}}
var Hh=W("dl.w",function(a,b,c){function d(){var g=G(a,b);(e=tb(g)&&Ug(a,g,c))||(f=Pe(a,d,1E3,"ec.dl"))}var e,f=0;d();return function(){return Oe(a,f)}});function Ih(a){var b=G(a,"ecommerce");if(Ra(b))return a=nb(qb(Ch),L(b)),a=E(function(c,d){c[d]=b[d];return c},{},a),0===L(a).length?void 0:a}
function Jh(a,b,c,d){if(c){var e=G(d,"ecommerce")||{};var f=G(d,"event")||"";e=Ra(e)&&Ha(f)?Gh(f,e):void 0;if(!e)a:{e=d;if(f=!tb(d))f=eb(d),f=a.isFinite(f)&&!a.isNaN(f)&&"[object Number]"===Object.prototype.toString.call(f);f&&(e=Fa(e));if(tb(e)){var g=p(e);e=g.next().value;f=g.next().value;g=g.next().value;if(Ha(f)&&Ra(g)&&"event"===e){e=Gh(f,g);break a}}e=void 0}if(d=e||Ih(d))e={},Ed(a,(e.counterKey=b,e.name="ecommerce",e.data=d,e)),a={},b={},c((b.__ym=(a.ecommerce=[d],a),b))}}
function Kh(a,b,c){var d;a=[Hh(a,b,function(e){d=e;e.Xa.C(c)}),function(){d&&d.unsubscribe()}];return A([Od,a],J)}var Lh=W("p.e",function(a,b){var c=og(a,b);if(c){var d=P(a);c=c.params;var e=V(a,"h.ee",A([a,O(b),c],Jh));return b.kb?(d.A("ecs",0),Kh(a,b.kb,e)):eg(b,function(f){if((f=G(f,"settings.ecommerce"))&&Ha(f))return d.A("ecs",1),Kh(a,f,e)})}});
function Mh(a,b,c,d,e){function f(k){return z(d)?d(k)?a.NodeFilter.FILTER_ACCEPT:a.NodeFilter.FILTER_REJECT:a.NodeFilter.FILTER_ACCEPT}e=void 0===e?-1:e;var g=void 0===g?!1:g;var h=f(b);if(z(c)&&(g||h===a.NodeFilter.FILTER_ACCEPT)&&(h&&c(b),!we(b)))for(b=a.document.createTreeWalker(b,e,d?{acceptNode:f}:null,!1);b.nextNode()&&!1!==c(b.currentNode););}var Nh=y(function(a){return R("[^\\d<>]*",a.split(""))}),Oh=y(function(a){return new RegExp(Nh(a),"g")});
function Ph(a){return new RegExp("(?:"+R("|",J(Nh,L(a)))+")")}function Qh(a){var b={7:"8",8:"7"};return 11===a.length&&b[a[0]]?""+b[a[0]]+a.slice(1):a}function Rh(a,b){for(var c=[],d=a.split(""),e=b.split(""),f=0,g=0;g<a.length&&!(f>=e.length);g+=1){var h=d[g];"0"<=h&&"9">=h?(c.push(e[f]),f+=1):c.push(d[g])}return R("",c)+b.slice(f+1)}function Sh(){return $a(function(a,b){var c=p(J(nd,b)),d=c.next().value;c=c.next().value;a[d]={ba:c,Ia:b};var e=Qh(d);e!==d&&(a[e]={ba:Qh(c),Ia:b});return a},{})}
function Th(a,b,c){if(!c)return[];var d=[],e=Ph(b),f=["script","style"];Mh(a,c,function(g){var h=G(g,"parentNode.nodeName")||"";g===c||I(h.toLowerCase(),f)||(h=ob(e.exec(g.textContent||"")||[]),J(function(k){var l=nd(k);Pa(b[l])||d.push({Bb:"text",oa:g,Fa:l,ba:Rh(k,b[l].ba),Ic:g.textContent||""})},h))},function(g){return e.test(g.textContent||"")?1:0},a.NodeFilter.SHOW_TEXT);return d}
function Uh(a,b){var c=a.document.body;if(!c)return[];var d=Ph(b);return E(function(e,f){var g=G(f,"href");try{var h=decodeURI(g||"")}catch(n){h=""}var k=h;if("tel:"===k.slice(0,4)){var l=p(d.exec(k)||[]).next().value;h=l?nd(l):"";var m=b[h];Pa(m)||!h&&"*"!==m.Ia[0]||(e.push({Bb:"href",oa:f,Fa:h,ba:Rh(l,b[h].ba),Ic:g}),g=nd(k.slice(4)),g=Sh()([h?m.Ia:[g,""]]),Md(e,Th(a,g,f)))}return e},[],ub(c.querySelectorAll("a")))}
function Vh(a,b){Se(a)(Qe(u,function(){var c=a.document.body,d={};d=(d.attributes=!0,d.childList=!0,d.subtree=!0,d);ua("MutationObserver",a.MutationObserver)&&(new MutationObserver(b.N)).observe(c,d)}))}function Wh(a,b){function c(){e=0;f&&(f=!1,e=Pe(a,c,1E3),d.N(g))}var d=Te(a),e,f=!1,g;b.C(function(h){f=!0;g=h;e||c();return u});return d}
var Xh=y(function(a){return Tb(a)||!oh(a)}),Yh=y(function(a){a=U(a);a=$c(a.search.substring(1));return{id:Nb(a["_ym_status-check"]||""),lang:a._ym_lang||"ru"}}),Zh=/[\*\.\?\(\)]/g,$h=y(function(a,b,c){try{var d=c.replace("\\s"," ").replace(Zh,"");b={};gg(a,"").warn("nnw",(b.name=d,b))}catch(e){}},Ba),ai=W("r.nn",function(a){zd(a)&&Ug(a,sa,function(b){b.Xa.C(function(c){var d=p(c);c=d.next().value;d=d.next().value;$h(a,d,c);sa.splice(100)})})});
function bi(a,b){return{H:function(c,d){qf(c)?d():eg(b,function(e){if(e=G(e,"settings.hittoken")){var f={};e=(f.hittoken=e,f);c.B=M(c.B||{},e)}d()})}}}
var ci=y(Ad,O),di=W("fpi",function(a){var b=Gc(a);if(b&&!a.document.hidden){var c=P(a).O;c("fpe",1);var d=Fc(a).C(a,["visibilitychange","webkitvisibilitychange"],function(){a.document.hidden&&(c("fht",b.now()),d())})}}),ei="FB_IAB FBAV OKApp GSA/ yandex yango uber EatsKit YKeyboard iOSAppUslugi YangoEats PassportSDK".split(" "),fi=y(function(a){var b=yb(a);a=b.Ob;if(!b.sb)return!1;b=Wa("indexOf",a);b=Jb(F(b,pa(-1),Ca),ei);var c=/CFNetwork\/[0-9][0-9.]*.*Darwin\/[0-9][0-9.]*/.test(a),d=/YaBrowser\/[\d.]+/.test(a),
e=/Mobile/.test(a);return b||c||d&&e||!/Safari/.test(a)&&e}),gi=y(function(a){var b=zb(a);return b?Ma(b,"YangoEats")||Yb(a):!1}),hi=[],ii=!1,ji=!1;function ki(a){if(hi.length){var b=hi.shift();ji?b():Pe(a,b,100)}else ii=!1}function li(a,b,c){c=void 0===c?1:c;var d=void 0===d?Uc:d;ji=Infinity===c;return ra(function(e,f){function g(){try{var k=b(d(a,c));h=h.concat(k)}catch(l){return e(l)}b(Rc);if(b(Oc))return f(h),ki(a);ji?(b(d(a,1E4)),f(h),ki(a)):Pe(a,g,100)}var h=[];ii?hi.push(g):(ii=!0,g())})}
function mi(a){var b=Rb(qc);return Array.prototype.sort.call(b,a)}var ni=t(function(a,b){return P(b).m(a,null)});function oi(a,b){var c=G(b,"__ym.turbo_uid");c&&P(a).O("tpuid",c)}
var pi=y(function(a){return z(G(a,"yandex.getSiteUid"))?a.yandex.getSiteUid():null}),qi=[["domainLookupEnd","domainLookupStart"],["connectEnd","connectStart"],["responseStart","requestStart"],["responseEnd","responseStart"],["fetchStart","navigationStart"],["redirectEnd","redirectStart"],[function(a,b){return G(b,"redirectCount")||G(a,"navigation.redirectCount")}],["domInteractive","domLoading"],["domContentLoadedEventEnd","domContentLoadedEventStart"],["domComplete","navigationStart"],["loadEventStart",
"navigationStart"],["loadEventEnd","loadEventStart"],["domContentLoadedEventStart","navigationStart"]],ri=[["domainLookupEnd","domainLookupStart"],["connectEnd","connectStart"],["responseStart","requestStart"],["responseEnd","responseStart"],["fetchStart"],["redirectEnd","redirectStart"],["redirectCount"],["domInteractive","responseEnd"],["domContentLoadedEventEnd","domContentLoadedEventStart"],["domComplete"],["loadEventStart"],["loadEventEnd","loadEventStart"],["domContentLoadedEventStart"]],si=
{},ti=(si.responseEnd=1,si.domInteractive=1,si.domContentLoadedEventStart=1,si.domContentLoadedEventEnd=1,si.domComplete=1,si.loadEventStart=1,si.loadEventEnd=1,si.unloadEventStart=1,si.unloadEventEnd=1,si.secureConnectionStart=1,si),ui=y(Bd);
function vi(a,b,c){return J(function(d){var e=p(d),f=e.next().value;e=e.next().value;if(z(f))return f(a,b)||null;if(1===d.length)return b[f]?Math.round(b[f]):null;var g;!(g=b[f]&&b[e])&&(g=0===b[f]&&0===b[e])&&(g=p(d),d=g.next().value,g=g.next().value,g=!(ti[d]||ti[g]));if(!g)return null;f=Math.round(b[f])-Math.round(b[e]);return 0>f||36E5<f?null:f},c)}
function wi(a,b){var c=a.length?J(function(d,e){var f=b[e];return f===d?null:f},a):b;a.length=0;J(F(x,Wa("push",a)),b);return nb(pa(null),c).length===a.length?null:c}
var xi={},yi=(xi.am="com.am",xi.tr="com.tr",xi.ge="com.ge",xi.il="co.il",xi["\u0440\u0444"]="ru",xi["xn--p1ai"]="ru",xi["\u0431\u0435\u043b"]="by",xi["xn--90ais"]="by",xi),zi={"mc.edadeal.ru":/^([^/]+\.)?edadeal\.ru$/,"mc.yandexsport.ru":/^([^/]+\.)?yandexsport\.ru$/,"mc.kinopoisk.ru":/^([^/]+\.)?kinopoisk\.ru$/},Ai={},Bi=(Ai.ka="ge",Ai.ro="md",Ai.tg="tj",Ai.tk="tm",Ai.et="ee",Ai.hy="com.am",Ai.he="co.li",Ai.ky="kg",Ai.be="by",Ai.tr="com.tr",Ai.kk="kz",Ai),Ci=/^https?:\/\//,Di={1882689622:1,2318205080:1,
3115871109:1,1996539654:1,2065498185:1,823651274:1,12282461:1,1555719328:1,1417229093:1,138396985:1};function Ei(a,b){var c=mi(function(d,e){return d[1].V>e[1].V?1:-1});c=J(function(d){var e=p(d);d=e.next().value;var f=e.next().value.Wa;e=db(b,d)&&!Qa(b[d]);d=b[d]!==(f||x)(void 0);return jb(e&&d)},c);return Ob(R("",c))}var Fi="ar:1:pv:1:v:"+N.da+":vf:"+la.version,Gi=N.ia+"//"+lc+"/watch/"+N.Sb;
function Hi(a,b){try{var c=p(b),d=p(c.next().value);d.next();var e=d.next().value}catch(f){return function(){return Q.resolve()}}return function(f){var g={};g=(g["browser-info"]=Fi,g["page-url"]=a.location&&""+a.location.href,g);return e&&(f=ne(a,f))?e(Gi,{Ea:g,Y:[],K:"site-info="+Yc(f)})["catch"](u):Q.resolve()}}
var Ii={},Ji=W("exps.int",function(a,b){var c={};return c.experiments=function(d,e,f){if(Ha(d)&&!(0>=d.length)){var g=$f(a,"e",b),h=Lg(b).url,k={},l={};d=g({D:Id((k.ex=1,k.ar=1,k)),B:(l["page-url"]=h||U(a).href,l.exp=d,l)},b);return Kg(a,"exps.s",d,e||u,f)}},c}),Ki=W("p.tpg",function(a,b){oi(a,b.G)}),Li=[],Mi=W("p.fh",function(a,b){b=void 0===b?!0:b;var c=ue(a),d=T(a),e=c.m("wasSynced"),f={id:3,L:"0"};if(b&&e&&e.time+864E5>d(S))return Q.resolve(e);e={};var g={};return $f(a,"f",f)({D:Id((e.pv=1,e)),
B:(g["page-url"]=U(a).href,g["page-ref"]=a.document.referrer,g)},f).then(function(h){var k={};h=(k.time=d(S),k.params=G(h,"settings"),k.bkParams=G(h,"userData"),k);c.A("wasSynced",h);return h})["catch"](V(a,"f.h"))}),Ni=y(function(a){a=U(a).hostname.split(".");return a[a.length-1]}),Oi=y(function(a){return-1!==U(a).hostname.search(/(?:^|\.)(?:ya|yandex|beru|kinopoisk|edadeal)\.(?:\w+|com?\.\w+)$/)}),Pi=RegExp("^(.*\\.)?((yandex(-team)?)\\.(com?\\.)?[a-z]+|(auto|kinopoisk|beru|bringly)\\.ru|ya\\.(ru|cc)|yadi\\.sk|yastatic\\.net|.*\\.yandex|turbopages\\.org|turbo\\.site|diplodoc\\.(com|tech)|datalens\\.tech|white-label\\.yango-tech\\.com|al-sadhan\\.com|spar\\.sa)$"),
Qi=y(function(a){a=U(a).hostname;var b=!1;a&&(b=-1!==a.search(Pi));return b});function Ri(a,b){this.l=a;this.type=b}Ri.isEnabled=function(a){return!!a.JSON};Ri.prototype.Ha=function(a){return Re(ne(this.l,a))};function Si(a,b){return{H:function(c,d){var e=c.B;e.wmode="0";e["wv-hit"]=e["wv-hit"]||""+Je(a);e["page-url"]=e["page-url"]||U(a).href;var f={};e={$:{T:"webvisor/"+b.id},I:M(c.I||{},{ga:(f["Content-Type"]="text/plain",f),hb:"POST"}),B:e};M(c,e);d()}}}
var Ti="resize scroll mousemove mousedown click windowfocus keydown orientationchange change focus touchmove touchstart".split(" "),Ui="id pageTitle stamp chars authors updateDate publicationDate pageUrlCanonical topics rubric".split(" ");
function Vi(a,b,c,d,e){var f=this;this.xa=!1;this.meta={};this.scroll={x:0,y:0};this.involvedTime=this.xb=0;this.Ua=this.zb="";this.J=[];this.$a=this.Jc=0;this.ha={h:0,w:0};this.buffer=[];this.Tb=Ui;this.flush=function(){f.$a=Pe(f.l,f.flush,2500);var g=f.Pa();if(f.buffer.length||g){var h=xb(f.buffer);g&&h.push(g);f.zb=f.Ua;f.Dc.Ha(h)(Qe(V(f.l,"p.b.st"),function(k){k&&f.Cc(k)}))}};this.Cc=d;this.Dc=c;this.sa=Va(this.sa,this);this.Pa=Va(this.Pa,this);this.flush=Va(this.flush,this);this.l=a;this.ea=
e;this.Ga=b;this.Sa="pai"+b.id;Wi(this);this.lb=Fc(this.l);this.time=T(this.l);Xi(this);this.Qa=P(this.l);this.gb=null}aa=Vi.prototype;aa.start=function(){this.$a=Pe(this.l,this.flush,2500);if(!this.xa){this.lb.C(this.l,Ti,this.sa);var a=this.Qa.m(this.Sa,[]),b=!a.length;a.push(Va(this.rc,this));this.Qa.O(this.Sa,a);b&&this.Eb();this.gb=Fc(this.l).C(this.l,["click"],Va(this.Ec,this));this.sa({type:"page",target:this.l})}};
aa.stop=function(){this.gb&&this.gb();this.lb.ra(this.l,Ti,this.sa);this.xa=!0;this.flush();Oe(this.l,this.$a)};aa.Eb=function(){var a=this;V(this.l,"p.ic"+this.Ga.id,function(){if(!a.xa){var b=a.Qa.m(a.Sa),c=Yi(a.Ga);J(function(d){var e=J(function(f){return M({},f)},c);z(d)&&d(e)},b);a.Jc=Pe(a.l,Va(a.Eb,a),1E3,"p")}})()};aa.rc=function(a){this.xa||(Zi(this,a),$i(this),aj(this))};aa.ac=function(a,b){return(a.Za||0)<=(b.Za||0)?b:a};
aa.Ec=function(a){if(this.J.length){a=bh(a);var b=U(this.l).hostname;a&&id(a.hostname)===id(b)&&(a=E(this.ac,this.J[0],this.J).id,b=Je(this.l),ve(this.l,this.ea.split(":")[0]).A("pai",a+"-"+b))}};
aa.sa=function(a){var b=this;V(this.l,"p.ec."+this.Ga.id,function(){try{var c=a.type;var d=a.target}catch(k){return}var e="page"===c;if("scroll"===c||e){var f=[b.l,b.l.document,b.l.document.documentElement,De(b.l)];I(d,f)&&Wi(b)}("resize"===c||e)&&Xi(b);c=b.time(S);var g=Math.min(c-b.xb,5E3);b.involvedTime+=Math.round(g);b.xb=c;if(b.meta&&b.scroll&&b.ha){var h=b.ha.h*b.ha.w;b.J=J(function(k){var l=M({},k),m=b.meta[l.id],n=He(k.ma);if(!m||rh("html",b.l,l.element)!==b.l.document.documentElement||!n)return l;
k=b.l.Math;m=k.max((b.scroll.y+b.ha.h-m.y)/m.height,0);var q=n.height*n.width,r=b.ha,v=n.top,w=n.bottom,D=n.left,B=r.w;r=r.h;var K=b.l.Math;n=K.min(K.max(n.right,0),B)-K.min(K.max(D,0),B);n*=K.min(K.max(w,0),r)-K.min(K.max(v,0),r);l.Za=n/h;l.visibility=n/q;if(.9<=l.visibility||.1<=l.Za)l.involvedTime+=g;l.maxScrolled=k.round(1E4*m)/1E4;return l},b.J);c={};d={};Ed(b.l,(d.name="publishers",d.counterKey=b.ea,d.data=(c.involvedTime=b.involvedTime,c.contentItems=J(function(k){var l={};return M((l.contentElement=
k.ma,l),k)},b.J),c),d))}})()};function Zi(a,b){var c=J(function(d){return d.id},a.J);a.J=a.J.concat(nb(function(d){return!I(d.id,c)},b))}function Xi(a){var b=p(Fe(a.l)||Ge(a.l)),c=b.next().value;b=b.next().value;a.ha={w:c,h:b}}
function $i(a){V(a.l,"p.um."+a.Ga.id,function(){var b=[];Wi(a);a.meta=E(function(c,d){if(rh("html",a.l,d.element)!==a.l.document.documentElement)return b.push(d),delete c[d.id],c;var e={};e=(e.id=d.id,e.involvedTime=Math.max(d.involvedTime,0),e.maxScrolled=d.maxScrolled||0,e.chars=d.update?d.update("chars")||0:0,e);if(d.ma){var f=He(d.ma);f&&(e.x=Math.max(Math.round(f.left)+a.scroll.x,0),e.y=Math.max(Math.round(f.top)+a.scroll.y,0),e.width=Math.round(f.width),e.height=Math.round(f.height))}c[d.id]=
e;return c},{},a.J);J(function(c){c=vb(a.l)(c,a.J);a.J.splice(c,1)},b)})()}aa.Pa=function(){var a=J(C(this.meta,G),L(this.meta));if(a.length&&(this.Ua=ne(this.l,a),this.zb!==this.Ua)){var b={},c={};return c.type="publishersHeader",c.data=(b.articleMeta=a||[],b.involvedTime=this.involvedTime,b),c}return null};
function aj(a){if(a.J.length){var b=J(function(c){var d=E(function(f,g){c[g]&&(f[g]=c[g]);return f},{},a.Tb);c.Ib=!0;var e={};return e.type="articleInfo",e.stamp=d.stamp,e.data=d,e},nb(function(c){return!c.Ib},a.J));b.length&&(a.buffer=a.buffer.concat(b),hg(a.l,a.ea,["pdf",b]))}}function Wi(a){a.scroll={x:a.l.pageXOffset||G(a.l,"document.documentElement.scrollLeft")||0,y:a.l.pageYOffset||G(a.l,"document.documentElement.scrollLeft")||0}}var bj={},cj=(bj[1]=500,bj[2]=500,bj[3]=0,bj);
function dj(a,b,c){var d=b.getAttribute("itemtype");c=ph('[itemprop~="'+c+'"]',b);return d?nb(function(e){return e.parentNode&&rh("[itemtype]",a,e.parentNode)===b},c):c}function ej(a,b,c){return(a=dj(a,b,c))&&a.length?a[0]:null}function fj(a){if(!a)return"";a=tb(a)?a:[a];return a.length?a[0].getAttribute("content")||xe(a[0]):""}function gj(a){return a?a.attributes&&a.getAttribute("datetime")?a.getAttribute("datetime"):fj(a):""}var hj=["topics","rubric","authors"];
function ij(a,b){var c=this;this.id="a";this.tb=!1;this.La={};this.Ac={"schema.org":"Article NewsArticle Movie BlogPosting Review Recipe Answer".split(" "),bd:["article"]};var d={};this.Nb=(d.Answer=3,d.Review=2,d);this.mb=y(function(e,f,g){var h={};hg(c.l,c.ea,"pfi",(h.field=e,h.itemField=f,h.value=g,h))},function(e,f,g){return""+e+f+g});this.Rc=function(e){J(function(f){e[f]&&(e[f]=E(function(g,h){var k=h.name,l=h.position;if(!k)return c.mb(f,"name",k),g;if("string"===typeof l){k=Kb(l);if(null===
k||c.l.isNaN(k))return c.mb(f,"position",l),g;h.position=k}g.push(h);return g},[],e[f]))},hj);return e};this.cc=y(function(e,f){var g={};hg(c.l,c.ea,["pcs",f],(g.chars=f.chars,g.limit=cj[f.type],g))});this.l=a;this.root=Ee(a);this.ea=b}function jj(a,b,c){var d;V(a.l,"P.s."+c,function(){d=a.La[c].call(a,b)})();return d}
function kj(a,b){var c=M({},b);if(a.tb&&!c.id&&I(b.type,[3,2])){var d=R(", ",J(H("name"),c.authors||[]));c.pageTitle=d+": "+c.pageTitle}if(!c.pageTitle){a:{d=c.ma;for(var e=1;5>=e;e+=1){var f=fj(qh("h"+e,d));if(f){d=f;break a}}d=void 0}c.pageTitle=d}c.pageUrlCanonical||(d=c.id,d=("string"!==typeof d?0:/^(https?:)\/\//.test(d))?c.id:(d=qh('[rel="canonical"]',a.root))?d.href:void 0,c.pageUrlCanonical=d);c.id||(c.id=c.pageTitle||c.pageUrlCanonical);return c}
ij.prototype.Oa=function(a){var b=this,c={},d=a.element;if(!d)return null;c.type=a.type;J(function(f){c[f]=jj(b,a,f)},L(this.La));var e=T(this.l);c.stamp=e(Nc);c.element=a.element;c.ma=d;c=this.Rc(kj(this,c));c.id=c.id?sh(c.id):1;c.update=function(f){return a.element?jj(b,a,f):void 0};return c};ij.prototype.getType=function(){return 1};ij.prototype.ob=function(){return[]};
function Yi(a){var b=a.ob(),c=1;return E(function(d,e){var f=a.Oa({element:e,type:a.getType(e)})||[];tb(f)||(f=[f]);f=E(function(g,h){var k=g.values,l=g.rb;h&&h.chars>cj[h.type]&&!I(h.id,l)?(k.push(h),l.push(h.id)):h&&h.chars<=cj[h.type]&&a.cc(h.id,h);return{values:k,rb:l}},{values:[],rb:J(H("id"),d)},f).values;return d.concat(J(function(g){var h={};g=M((h.index=c,h.Ib=!1,h.involvedTime=0,h),g);c+=1;return g},f))},[],b)}
function lj(){ij.apply(this,arguments);this.id="s";this.tb=!0;this.Oc=Wa("exec",new RegExp("schema.org\\/("+R("|",L(this.Nb))+")$"));var a={};this.La=(a.id=function(b){b=b.element;var c=ej(this.l,b,"identifier");return c?fj(c):(c=ej(this.l,b,"mainEntityOfPage"))&&c.getAttribute("itemid")?c.getAttribute("itemid"):null},a.chars=function(b){var c=0;b=b.element;for(var d=["articleBody","reviewBody","recipeInstructions","description","text"],e=0;e<d.length;e+=1){var f=ej(this.l,b,d[e]);if(f){c=fj(f).length;
break}}b=xe(b);0===c&&b&&(c+=b.length);return c},a.topics=function(b){var c=this,d=dj(this.l,b.element,"about");return J(function(e){var f={name:fj(e)};if(d=ej(c.l,e,"name"))f.name=fj(d);return f},d)},a.rubric=function(b){var c=this;(b=qh('[itemtype$="schema.org/BreadcrumbList"]',b.element))||(b=qh('[itemtype$="schema.org/BreadcrumbList"]',this.root));return b?J(function(d){return{name:fj(ej(c.l,d,"name")),position:fj(ej(c.l,d,"position"))}},dj(this.l,b,"itemListElement")):[]},a.updateDate=function(b){return(b=
ej(this.l,b.element,"dateModified"))?gj(b):""},a.publicationDate=function(b){return(b=ej(this.l,b.element,"datePublished"))?gj(b):""},a.pageUrlCanonical=function(b){b=dj(this.l,b.element,"url");if(b.length){var c=b[0];return c.href?c.href:fj(b)}return null},a.pageTitle=function(b){var c="",d=b.element,e=ej(this.l,d,"headline");e&&(c+=fj(e));(e=ej(this.l,d,"alternativeHeadline"))&&(c+=" "+fj(e));""===c&&((e=ej(this.l,d,"name"))||(e=ej(this.l,d,"itemReviewed")),e&&(c+=fj(e)));3===b.type&&(b=rh('[itemtype$="schema.org/Question"]',
this.l,d))&&(b=ej(this.l,b,"text"))&&(c+=fj(b));return c},a.authors=function(b){var c=this;b=dj(this.l,b.element,"author");return J(function(d){var e={};e=(e.name="",e);if(/.+schema.org\/(Person|Organization)/.test(d.getAttribute("itemtype")||"")){var f=ej(c.l,d,"name");f&&(e.name=fj(f))}e.name||(e.name=d.getAttribute("content")||xe(d)||d.getAttribute("href"));return e},b)},a)}lj.prototype=ea(ij.prototype);lj.prototype.constructor=lj;
if(ka)ka(lj,ij);else for(var mj in ij)if("prototype"!=mj)if(Object.defineProperties){var nj=Object.getOwnPropertyDescriptor(ij,mj);nj&&Object.defineProperty(lj,mj,nj)}else lj[mj]=ij[mj];lj.prototype.getType=function(a){a=a.getAttribute("itemtype")||"";return(a=this.Oc(a))?this.Nb[a[1]]:1};lj.prototype.Oa=function(a){return a.element&&xe(a.element).length?ij.prototype.Oa.call(this,a):null};
lj.prototype.ob=function(){var a=R(",",J(function(b){return'[itemtype$="schema.org/'+b+'"]'},this.Ac["schema.org"]));return ph(a,this.root)};function oj(a,b,c,d,e){d=Wf(a,c,d);b=Bf(a,e||c,b);var f=Wd(a,d,b);return function(g){g=M({I:{Y:["mms."+c]}},g);return f(g)}}var pj="et w v z i u vf".split(" "),qj={};lj&&(qj.schema=lj,qj.microdata=lj);
var rj=W("p.p",function(a,b){function c(l){var m=M({},k);m.I.K=l;return e(m)["catch"](V(a,"s.ww.p"))}var d=Ri.isEnabled(a)?new Ri(a,"8"):void 0;if(!ua("querySelectorAll",a.document.querySelectorAll)||!d)return Q.resolve();var e=oj(a,b,"p",["f","x"],[[lf(pj),1],[Si,1]]),f=Id(),g=ve(a,b.id),h=g.m("pai");h&&(g.va("pai"),f.A("pai",h));g={};var k={B:(g["wv-type"]=d.type,g),D:f,I:{}};return eg(b,V(a,"ps.s",function(l){if(l=G(l,"settings.publisher.schema")){Hg(b)&&(l="microdata");var m=qj[l];if(m&&d){var n=
O(b);m=new m(a,n);m=new Vi(a,m,d,c,n);m.start();var q={};hg(a,n,"ps",(q.schema=l,q));return Va(m.stop,m)}}}))});function sj(a,b,c,d,e){d=void 0===d?1:d;e=void 0===e?"itc":e;b=Wc(b,c);li(a,b,d)(Qe(V(a,e),u))}var tj=y(function(a){var b=P(a),c=b.m("isEU");if(Pa(c)){var d=Nb(rd(a,"is_gdpr")||"");if(I(d,[0,1]))b.A("isEU",d),c=!!d;else if(a=ue(a).m("wasSynced"),a=G(a,"params.eu"))b.A("isEU",a),c=!!a}return c},function(a){return P(a).m("isEU")}),uj=W("i.ep",function(a){tj(a)});
function vj(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}var wj=N.ia+"//"+lc+"/metrika";function xj(a){return{H:function(b,c){var d=b.D;if(d){var e=P(a).m("adBlockEnabled");e&&d.A("adb",e)}c()}}}function yj(a,b){var c=a.document;if(I(c.readyState,["interactive","complete"]))jg(a,b);else{var d=Fc(a),e=d.C,f=d.ra,g=function(){f(c,["DOMContentLoaded"],g);f(a,["load"],g);b()};e(c,["DOMContentLoaded"],g);e(a,["load"],g)}}
var zj=C("9-d5ve+.r%7",x),Aj=W("ad",function(a,b){if(!b.Aa){var c=P(a);if(!c.m("adBlockEnabled")){var d=function(m){I(m,["2","1"])&&c.A("adBlockEnabled",m)},e=yd(a),f=e.m("isad");if(f)d(f);else{var g=C("adStatus",c.A),h=function(m){m=m?"1":"2";d(m);g("complete");e.A("isad",m,1200);return m},k=$f(a,"adb",b);if(!c.m("adStatus")){g("process");var l="metrika/a"+zj().replace(/[^a-v]+/g,"")+"t.gif";yj(a,function(){return k({$:{T:l}}).then(C(!1,h))["catch"](C(!0,h))})}}}}}),Bj=y(Ad);
function Cj(a){var b=Bj();b.Hc||(b.Hc=a)}C(ae("ccf"),xc);
function Dj(a,b,c,d,e){if(b.ja&&b.na&&(b.ja===a.ja&&b.na===a.na||M(a,b,{M:{},Ma:!0}),0<e&&Md(a.S,[e]),J(function(f){var g=p(f);f=g.next().value;g=g.next().value;var h={},k={};M(a.M,(k[f]=(h[g]=+(a.M[f]&&a.M[f][g]?a.M[f][g]:0),h),k))},d),J(function(f){var g=p(f);f=g.next().value;g=g.next().value;var h={},k={};M(a.M,(k[f]=(h[g]=1+(a.M[f]?a.M[f][g]:0),h),k))},c),a.ub&&(a.Ma||c.length))){if(b=og(a.l,a.jb))c={},b.params("__ym","phc",(c.clientId=a.ja,c.orderId=a.na,c.service_id=a.Kb,c.phones=a.M,c.performance=
a.S,c));a.Ma=!1}}var Ej=y(function(a,b,c){function d(k){return e(a,b,k)?h[k.Fa]&&h[k.Fa].Ia:null}var e=c.Nc,f={},g=void 0===c.uc?(f.href=!0,f.text=!0,f):c.uc,h;return function(k){return new Q(function(l,m){k&&k.length||m();h=Sh()(k);Se(a)(Qe(C({M:[],S:0},l),function(){var n=T(a),q=n(S),r=g.href?Uh(a,h):[],v=g.text?Th(a,h,a.document.body):[];l({M:nb(tb,ob(J(d,r.concat(v)))),S:n(S)-q})}))})}});
function Fj(a,b,c){a=Oh(c.Fa);if("href"===c.Bb){var d=c.oa;b=d.href;c=b.replace(a,c.ba);if(b!==c)return d.href=c,!0}else if((b=null===(d=c.oa.textContent)||void 0===d?void 0:d.replace(a,c.ba))&&b!==c.oa.textContent)return c.oa.textContent=b,!0;return!1}var Gj=y(me,Ba);
function Hj(a,b,c){b=xd(a,void 0,b);b=Gj(a,b.m("phc_settings")||"");var d=G(b,"clientId"),e=G(b,"orderId"),f=G(b,"service_id"),g=G(b,"phones")||[];return d&&e&&g&&f?Ej(a,c.jb,{Nc:Fj})(g).then(function(h){return Dj(c,{ja:d,na:e,Kb:f},h.M,g,h.S)})["catch"](u):Q.resolve()}
var Ij=W("phc.p",function(a,b){if(!Xh(a))return eg(b,function(c){var d=b.id,e=xd(a,void 0,d),f=e.m("phc_settings")||"";if(c=G(c,"settings.phchange")){var g=ne(a,c)||"";g!==f&&e.A("phc_settings",g)}else f&&(c=Gj(a,f));e=G(c,"clientId");f=G(c,"orderId");c=G(c,"phones")||[];e&&f&&c.length&&(f={ja:"",na:"",Kb:0,M:{},S:[],ub:!1,Ma:!0,l:a,jb:b},M(f,{ub:!0}),Hj(a,d,f),c=Te(a),e=Wh(a,c),d=Va(Hj,null,a,d,f),e.C(d),Vh(a,c))})}),Jj="architecture bitness model platformVersion uaFullVersion fullVersionList".split(" "),
Kj=cd("uah",function(a){if(!ua("getHighEntropyValues",G(a,"navigator.userAgentData.getHighEntropyValues")))return Q.reject("0");try{return a.navigator.userAgentData.getHighEntropyValues(Jj).then(function(b){if(!Ra(b))throw"2";return b},function(){throw"1";})}catch(b){return Q.reject("3")}}),Lj=new RegExp(R("|","yandex.com/bots;Googlebot;APIs-Google;Mediapartners-Google;AdsBot-Google;FeedFetcher-Google;Google-Read-Aloud;DuplexWeb-Google;Google Favicon;googleweblight;Lighthouse;Mail.RU_Bot;StackRambler;Slurp;msnbot;bingbot;www.baidu.com/search/spi_?der.htm".split(";")).replace(/[./]/g,
"\\$&")),Mj=y(function(a){var b=zb(a);return(b=Lj.test(b))?Q.resolve(b):Kj(a).then(function(c){try{return E(function(d,e){return d||Lj.test(e.brand)},!1,c.brands)}catch(d){return!1}},C(!1,x))}),Nj=["0","1","2","3"],Oj=Nj[0],Pj=Nj[1],Qj=Nj[2],Rj=["GDPR-ok-view-detailed-0","GDPR-ok-view-detailed-1","GDPR-ok-view-detailed-2","GDPR-ok-view-detailed-3"],Sj=["GDPR-ok-view-default","GDPR-ok-view-detailed"].concat(Rj);
function Tj(a){if(I(a,["GDPR-ok-view-default","GDPR-ok-view-detailed"]))return Oj;a=a.replace("GDPR-ok-view-detailed-","");return I(a,Nj)?a:Oj}var Uj="GDPR-ok GDPR-cross GDPR-cancel 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 GDPR-settings GDPR-ok-view-default GDPR-ok-view-detailed 21 22 23".split(" ").concat(Rj).concat(["28","29","30","31"]),Vj="3 13 14 31 15 16 17 28".split(" "),Wj=F(Fb(H("ymetrikaEvent.type")),pb(qb(Uj)));function Xj(a,b,c){a=c||cc(a);return I(a,b)?a:"en"}
var Yj={sc:!0,url:"https://yastatic.net/s3/gdpr/v3/gdpr",yb:"",wb:"az be en es et fi fr hy ka kk ky lt lv no pt ro ru sl tg tr uz cs da de el hr it nl pl sk sv".split(" ")},Zj=cd("gdpr",function(a,b,c,d,e){function f(n){b("10");c.C(Sj,function(q){q=q.type;var r={};l.Fb((r.type=q,r));n({value:Tj(q)})})}var g=void 0===e?Yj:e;e=g.url;var h=g.yb,k=g.sc;g=Xj(a,g.wb,d.Tc);var l=Rg(a,d);if(!l)return Q.resolve({value:Oj,Ra:!0});if(a._yaGdprLoaded)return new Q(function(n){b("7");f(n)});var m=Cf(a,{src:""+
e+(k?"":g)+h+".js"});return new Q(function(n,q){m?(b("7"),m.onerror=function(){b("9");var r={};l.Fb((r.type="GDPR-ok-view-default",r));n(null)},m.onload=C(n,f)):(b("9"),q(ae("gdp.e")))})});function ak(a,b){var c=Rg(a,b);c&&c.aa.C(["isYandex"],function(){var d={};return d.type="isYandex",d.isYandex=Qi(a),d})}
function bk(a,b,c){var d=Rg(a,c);return new Q(function(e){if(d){var f=d.aa,g=F(C("4",b),C(null,e)),h=Pe(a,g,2E3,"gdp.f.t"),k={};d.Hb((k.type="isYandex",k)).then(function(l){l.isYandex?(b("5"),f.C(Sj,function(m){m=p(m);m.next();m=m.next().value.type;e({value:Tj(m)})})):(b("6"),e(null))})["catch"](g).then(A([a,h],Oe))}else e({value:Pj,Ra:!0})})}
var ck={},dk=(ck["GDPR-ok"]="ok",ck["GDPR-ok-view-default"]="ok-default",ck["GDPR-ok-view-detailed"]="ok-detailed",ck["GDPR-ok-view-detailed-0"]="ok-detailed-all",ck["GDPR-ok-view-detailed-1"]="ok-detailed-tech",ck["GDPR-ok-view-detailed-2"]="ok-detailed-tech-analytics",ck["GDPR-ok-view-detailed-3"]="ok-detailed-tech-other",ck);function ek(a,b){if(Qi(a)){var c=Tg(a),d=og(a,b);d=d&&d.params;c=J(C(dk,G),Wj(c));d&&c.length&&d("gdpr",ob(c))}}
var fk="az be en es et fi fr hy ka kk ky lt lv no pt ro ru sl tg tr uz ar he sr uk zh".split(" "),gk=[],hk=Wa("push",gk),ik=y(function(a,b){var c=b.m("gdpr");return I(c,Nj)?"-"+c:""});
function jk(a,b,c,d){if(!c.D||nc(b.L))d();else{var e=Tg(a),f=C(e,Sg),g=xd(a,""),h=function(){var q=R(",",J(Aa(Uj),Wj(e)));q=""+q+ik(q,g);ge(c,"gdpr",q);d()};if(b.Sc)f("31"),h();else if(3===b.id)h();else{var k=P(a),l=k.m("f1");if(l)l(h);else if(l=Wj(e),Jb(qb(Uj),l))h();else if(g.m("yandex_login"))f("13"),g.A("gdpr",Oj,525600),h();else{l=Qi(a);var m=U(a);var n=/(^|\w+\.)yango(\.yandex)?\.com$/.test(m.hostname)?{url:"https://yastatic.net/s3/taxi-front/yango-gdpr-popup/",version:2,wb:fk,yb:"_inversed_buttons"}:
void 0;l||n?(l=g.m("gdpr"),I(l,Nj)?(f(l===Pj?"12":"3"),h()):fi(a)||gi(a)?(f("17"),h()):Mj(a).then(x,u).then(function(q){q?(f("28"),h()):(hk(h),k.A("f1",hk),q=p(Li).next().value,q(a).then(H("params.eu")).then(function(r){if(r||Ma(m.href,"yagdprcheck=1")||g.m("yaGdprCheck")){g.A("gdpr_popup",Pj);ak(a,b);if(dc(a))return bk(a,f,b);var v=Wg(a,e);if(v)return r=Zj(a,f,v,b,n),r.then(A([a,b],ek)),r}r||f("8");return Q.resolve({value:Oj,Ra:!0})}).then(function(r){g.va("gdpr_popup");if(r){var v=r.value;r=r.Ra;
I(v,Nj)&&g.A("gdpr",v,r?void 0:525600)}v=Wc(gk,Nd);li(a,v,20)(Qe(V(a,"gdr"),u));k.A("f1",Nd)})["catch"](V(a,"gdp.a")))})):(f("14"),h())}}}}var kk=lc.split("."),lk=kk.pop(),mk=R(".",kk),nk={};function ok(a){var b=wj+"/tag_debug.js?ver="+N.da+"&b=p";nk[b]||(nk[b]={Bc:Cf(a,{src:b}),state:0});return nk[b]}function pk(a,b){function c(){e.state=1;b()}function d(){e.state=2}var e=ok(a),f=e.Bc,g=e.state;f&&2!==g?1===g?c():(g=Fc(a),g.C(f,["load"],c),g.C(f,["error"],d)):d()}var qk=y(Ad,O);
function rk(a,b,c){var d=qk(b).yc;if(!d)throw vc("im.no");pk(a,function(){var e=P(a).m("ytmm");(e=G(e,"tag_debug.init"))&&e(d,c,N.da)})}var sk=y(Bd);function tk(a){a=cc(a);return Bi[a]||"ru"}function uk(a){a=Ni(a);return yi[a]||a}var vk=y(function(){var a=E(function(b,c){"ru"!==c&&(b[c]=mk+"."+c);return b},{},gd);J(function(b){a[b]=b},L(zi));return a}),wk=y(function(a){a=U(a).hostname;return(a=Gd(F(H("1"),bb("test"),oa(Nd)(a)),Rb(zi)))&&a[0]});
function xk(a,b){var c=tk(a),d=[wk(a)||uk(a)];Oi(a)&&d.push(c);var e=T(a);c=ue(a);var f=c.m("synced",{});d=nb(function(g){if(b[g]){var h=(f[g]||1)+1440<e(Lc);h&&delete f[g];return h}},d);c.A("synced",f);return J(function(g){return{Gc:b[g],tc:g}},d)}
var yk=function(a,b){return function(c,d){if(hc(c)||Bb(c))return{};var e=O(d);e=vk(e);var f=xk(c,e),g=P(c),h=dc(c);return{H:function(k,l){var m=k.D,n=Oi(c);m=!(m&&m.m("pv"));if(!n||h||m||!f.length)return l();if(g.m("startSync"))sk(c).push(l);else{g.A("startSync",!0);n=A([c,f,d.id,u,!1],a);m=p(Li).next().value;if(!m)return l();m(c).then(n).then(l,F(qa(l),V(c,b)))["catch"](u)}}}}}(function(a,b,c,d,e){var f=T(a),g=P(a),h=ue(a);d=Wf(a,"c");var k=Ld(a,d),l=vj()+vj()+"-"+vj()+"-"+vj()+"-"+vj()+"-"+vj()+
vj()+vj();Cj(l);return E(function(m,n){function q(){var w=h.m("synced");g.A("startSync",!1);w&&(w[n.tc]=r,h.A("synced",w));w=sk(a);J(Nd,w);xb(w)}var r,v={};v=k({I:{Y:["sync.cook"],cb:1500},B:(v.scid=l,v.cid=""+c,v)},[N.ia+"//"+n.Gc+"/sync_cookie_image_check"+(e?"_secondary":"")]).then(function(){r=f(Lc);q()})["catch"](function(){r=f(Lc)-1435;q()});v=C(v,x);return m.then(v)},Q.resolve(),b)["catch"](V(a,"ctl"))},"sy.c"),zk={},Ak=(zk.brands="chu",zk.architecture="cha",zk.bitness="chb",zk.uaFullVersion=
"chf",zk.fullVersionList="chl",zk.mobile="chm",zk.model="cho",zk.platform="chp",zk.platformVersion="chv",zk);function Bk(a){return Ha(a)?a:tb(a)?R(",",J(function(b){return'"'+b.brand+'";v="'+b.version+'"'},a)):Qa(a)?"":a?"?1":"?0"}function Ck(a){return"che\n"+a}function Dk(a){var b=E(function(c,d){var e=p(d),f=e.next().value;e=e.next().value;(f=Bk(a[f]))&&c.push(""+e+"\n"+f);return c},[],Rb(Ak));return R("\n",b)}var Ek=y(function(a){return Kj(a).then(Dk,Ck)});
function Fk(a){return{H:function(b,c){Ek(a).then(function(d){b.B||(b.B={});b.B.uah=d;c()},c)}}}function Gk(a,b){if("https://oauth.yandex.ru"===G(b,"origin")&&G(b,"source.window")&&"_ym_uid_request"===G(b.data,"_ym")){var c=b.source,d={};d=(d._ym_uid=a,d);c.postMessage(d,"https://oauth.yandex.ru")}}
var Hk=cd("ot",function(a,b){if(jc(a)){var c=Fc(a);return eg(b,V(a,"ot.s",function(d){if(G(d,"settings.oauth")){var e=[],f=cf(a,b);e.push(c.C(a,["message"],V(a,"ot.m",C(f,Gk))));Se(a)(Qe(u,V(a,"ot.b",function(){function g(n){var q=n.href;if(q&&wg(q,"https://oauth.yandex.ru/")&&!Ma(q,"_ym_uid=")){q=Ma(q,"?")?"&":"?";var r={};n.href+=""+q+ad((r._ym_uid=f,r.mc="v",r));c.C(n,["click"],V(a,"ot.click",function(){var v="et="+k(S);n.href+="&"+v}))}}var h=a.document.body,k=T(a),l=ph("a",h);J(g,l);if(ua("MutationObserver",
a.MutationObserver)){l=new a.MutationObserver(V(a,"ot.m",C(function(n){n=n.addedNodes;for(var q=0;q<n.length;q+=1){var r=n[q];"A"===r.nodeName&&g(r)}},J)));var m={};m=(m.childList=!0,m.subtree=!0,m);l.observe(h,m);e.push(Va(l.disconnect,l))}})));return A([Od,e],J)}}))}}),Ik=W("p.cm",function(a){rc(a).O("mcs",W("p.cm.cs",function(b,c,d,e,f){if(og(a,c))return oj(b,c,d,e,f);xc(vc("cmws.cd"))})).O("wsfm",lf)}),Jk=W("destruct.e",function(a,b,c){return function(){var d=P(a),e=b.id;J(function(f,g){return z(f)&&
V(a,"dest.fr."+g,f)()},c);delete d.m("counters")[O(b)];delete a["yaCounter"+e]}});function Kk(a,b,c,d){return function(){var e=Fa(arguments);e=d.apply(null,da(e));return Pa(e)?og(a,b):e}}function Lk(a,b,c,d){return V(a,"cm."+c,d)}function Mk(a,b,c,d,e){if(!c.length)return e;c=J(function(f){return A([a,b,d],f)},c);return F.apply(null,da(c))(e)}var Nk=P(window);Nk.O("hitParam",{});P(window).O("getCounters",Dg(window));rg.push(Eg);Zf["1"]=Yd;sg.push(Ng);Vf["1"]=Rf;yf(Jg,-1);
Af["1"]=[[Jg,-1],[$d,1],[sf,2],[lf(),3],[vf,4]];sg.push(Yg);
sg.push(W("p.ar",function(a,b){var c=$f(a,"a",b),d={};return d.hit=function(e,f,g,h,k,l){var m={};m={B:{},D:Id((m.pv=1,m.ar=1,m))};f=Ra(f)?{title:f.title,Ab:f.referer,G:f.params,ta:f.callback,l:f.ctx}:{title:f,Ab:g,G:h,ta:k,l:l};h=Lg(b);g=e||U(a).href;h.url!==g&&(h.ref=h.url,h.url=e);e=f.Ab||h.ref||a.document.referrer;h={};h=ig(a,b,"pv",(h.id=b.id,h.url=g,h.ref=e,h),f.G);k=M(m.F||{},{G:f.G,title:f.title});l={};m=c(M(m,{F:k,B:M(m.B||{},(l["page-url"]=g,l["page-ref"]=e,l))}),b).then(h);return Kg(a,
"p.ar.s",m,f.ta||u,f.l)},d}));Zf.a=Yd;Af.a=wf;Vf.a=Rf;sg.push(ah);Zf.g=Yd;Vf.g=Rf;Af.g=wf;
sg.push(W("cl.p",function(a,b){function c(n,q,r,v){v=void 0===v?{}:v;r?dh(a,b,{url:r,fa:!0,wa:n,Ba:q,sender:d,Pb:v}):g.warn("clel")}var d=$f(a,"2",b),e=[],f=O(b),g=gg(a,f),h=V(a,"s.s.tr",C(Bg(a,f),ch));f={l:a,ec:b,hc:e,sender:d,Yc:P(a),dc:ve(a,b.id),$c:Je(a),Mc:C(C(f,Cg(a)),F(Nd,H("trackLinks")))};f=V(a,"cl.p.c",C(f,eh));f=Fc(a).C(a,["click"],f);b.Mb&&h(b.Mb);var k=V(a,"file.clc",A([!0,!1],c)),l=V(a,"e.l.l.clc",A([!1,!0],c));e=V(a,"add.f.e.clc",fh(e));var m={};return m.file=k,m.extLink=l,m.addFileExtension=
e,m.trackLinks=h,m.u=f,m}));Af["2"]=wf;Zf["2"]=Yd;Vf["2"]=Rf;Zf.r=Xd("r");Vf.r=["f","x","j","i"];tg.push(W("p.r",function(a,b){var c=lh(a),d=$f(a,"r",b),e=V(a,"rts.p");return eg(b,A([function(f,g){var h={id:g.counterId,L:g.L},k={I:{K:g.xc},D:Id(g.$b),B:g.G,F:{qa:g.qa},$:{T:g.T}};g.X&&(k.X=fe(g.X));h=d(k,h)["catch"](e);return f.then(C(h,x))},Q.resolve(),c],E)).then(C(void 0,x))["catch"](e)}));
Z("r",function(a){return{H:function(b,c){var d=void 0===b.D?Id():b.D,e=b.F.qa,f=gh(a),g=d.m("rqnl",0)+1;d.A("rqnl",g);if(d=G(f,R(".",[e,"browserInfo"])))d.rqnl=g,hh(a);c()},ca:function(b,c){ih(a,b);c()}}},1);yf(jh,100);Z("1",jh,100);Z("n",jh,100);sg.push(nh);Z("n",$d,1);Z("n",sf,2);Z("n",lf(),3);Z("n",vf,3);Zf.n=Yd;Vf.n=Rf;M(qc,{ib:{V:"accurateTrackBounce"}});sg.push(Lh);he.push("ecommerce");M(qc,{kb:{V:"ecommerce",Wa:function(a){if(a)return!0===a?"dataLayer":""+a}}});od.push("_ym_debug");vg.unshift(ai);
var Ok={},Pk=(Ok.tp=F(Ba,Hg,ib),Ok.tpid=F(Ba,function(a){a=O(a);return Fg[a]&&Fg[a].Lc||null}),Ok);M(jf,Pk);yf(bi,20);Z("n",bi,20);Z("1",bi,20);vg.unshift(di);
jf.fp=function(a,b,c){if(c.B&&c.B.nohit)return null;c=P(a).m;if(!c("fpe"))return null;b=ci(b);if(b.jc)return null;c=c("fht",Infinity);a:{var d=G(a,"performance.getEntriesByType");if(z(d)){if(a=nb(F(x,H("name"),pa("first-contentful-paint")),d.call(a.performance,"paint")),a.length){a=a[0].startTime;break a}}else{var e=G(a,"chrome.loadTimes");d=gf(a);if(z(e)&&(e=e.call(a.chrome),e=G(e,"firstPaintTime"),d&&e)){a=1E3*e-d;break a}if(a=G(a,"performance.timing.msFirstPaint")){a-=d;break a}}a=void 0}return a&&
c>a?(b.jc=a,Math.round(a)):null};M(jf,{bu:pi,ds:function(a,b,c){if((void 0===c.B?{}:c.B).nohit)return null;a=Gc(a);if(!a)return null;var d=c=null;G(a,"getEntriesByType")&&(d=G(a.getEntriesByType("navigation"),"0"))&&(c=ri);if(!c){var e=G(a,"timing");e&&(c=qi,d=e)}if(!c)return null;a=vi(a,d,c);b=O(b);b=ui(b);return(b=wi(b,a))&&R(",",b)},td:function(a){return P(a).m("tpuid")}});
(function(){var a={};a.oo=ni("oo");a.yu=function(b){return(b=xd(b,"").m("yandexuid"))&&b.substring(0,25)};a.ecs=ni("ecs");a.cdl=ni("cdl");a.eco=y(Ei,F(Ba,O));M(le,a)})();Vf.er=Tf;(function(){var a=window;try{var b=Wf(a,"er"),c=Hi(a,b);de.push(function(d,e,f,g){var h={},k={},l={},m={},n={};c((n[d]=(m[N.da]=(l[e]=(k[f]=g?(h[a.location.href]=g,h):a.location.href,k),l),m),n))})}catch(d){}})();
qg.push(function(a,b){if(G(a,"disableYaCounter"+b.id)||G(a,"Ya.disableMetrica")){var c=O(b);delete P(a).m("counters",{})[c];xc(ae("oo.e"))}});xf.unshift(function(a){return{H:function(b,c){P(a).m("oo")||c()}}});yf(function(a,b){return{H:function(c,d){var e=c.B,f=c.D;!Ii[b.id]&&f.m("pv")&&b.exp&&!e.nohit&&(e.exp=b.exp,Ii[b.id]=!0);d()}}},-99);sg.push(Ji);Af.e=wf;Zf.e=Yd;Vf.e=Rf;M(qc,{exp:{V:"experiments"}});ke.experiments="ex";rg.push(Ki);
yf(function(a){return{H:function(b,c){b.F&&b.F.G&&oi(a,b.F.G);c()}}},2.5);Li.push(Mi);Zf.f=Yd;var Qk={};M(Vf,(Qk.f=Sf,Qk));Z("f",lf(),1);Z("f",mf,2);Z("f",bi,20);tg.push(rj);yf(xj,6);Z("1",xj,6);Z("adb");Z("n",xj,4);Vf.adb=Tf;Zf.adb=Wd;rg.push(Aj);Zf.d=Yd;Z("d",lf(["hid","u","v","vf"]),1);Vf.d=Tf;
Z("n",function(a,b){return{ca:function(c,d){if(!c.F||!c.F.force){var e=b.id===N.Xb?1:.002,f=.002;f=void 0===f?1:f;e=void 0===e?1:e;var g=Gc(a);if(g&&z(g.getEntriesByType)){f=Math.random()>f;var h=Math.random()>e;if(!f||!h){var k=g.getEntriesByType("resource"),l={},m={};g={};e=U(a).href;for(var n=0;n<k.length;n+=1){var q=k[n];var r=p(q.name.replace(Ci,"").split("?")).next().value;var v=r+"?",w=sh(v);ma[w]?r=[v,w,!0]:(v=sh(r),r=ma[v]?[r,v,!0]:[r,v,!1]);w=p(r);r=w.next().value;v=w.next().value;w=w.next().value;
var D={};D=(D.dns=Math.round(q.domainLookupEnd-q.domainLookupStart),D.tcp=Math.round(q.connectEnd-q.connectStart),D.duration=Math.round(q.duration),D.response=Math.round(q.responseEnd-q.requestStart),D);if("script"===q.initiatorType&&!f){var B={};m[r]=M(D,(B.name=q.name,B.decodedBodySize=q.decodedBodySize,B.transferSize=Math.round(q.transferSize),B))}!w&&!Di[v]||l[r]||h||(q={},l[r]=M(D,(q.pages=e,q)))}L(l).length&&(g.timings8=l);L(m).length&&(g.scripts=m);L(g).length&&(f={},h={},$f(a,"d",b)({D:Id((f.ar=
1,f.pv=1,f)),I:{K:ne(a,g)||void 0},B:(h["page-url"]=e,h)},{id:N.Zb,L:"0"})["catch"](V(a,"r.tim.ng2")))}}}d()}}},7);sg.push(Ij);rg.push(uj);M(qc,{Sc:{V:"yaDisableGDPR"},Tc:{V:"yaGDPRLang"}});xf.push(function(a,b){return{H:A([a,b],jk)}});od.push("gdpr");od.push("gdpr_popup");pd.push(function(a,b){var c=Tg(a);c=Wj(c);if(nb(qb(Vj),c).length)return!0;c=b(a,"gdpr");return I(c,[Oj,Qj])});
xf.push(function(a){return{H:function(b,c){var d=b.$||{},e;if(e=G(a,"document.referrer")){b:{if(e=Ef(a,e).host.match(hd)){var f=p(e);f.next();e=f.next().value;if(f=f.next().value){e=I(f,gd)?f:!1;break b}if(e){e=gd[0];break b}}e=!1}e=mk+"."+(e||lk)}else e=lc;b.$=M(d,{qb:[e]});c()}}});yf(yk,5);Z("1",yk,6);Vf.c=Tf;Zf.c=Ld;Z("1",Fk,7);yf(Fk,7);tg.push(W("p.ot",Hk));
vg.push(W("cdl",function(a){var b=P(a).O;if(a=G(a,"navigator.cookieDeprecationLabel"))try{a.getValue().then(C("cdl",b),A(["cdl","e"],b))}catch(c){b("cdl","d")}else b("cdl","na")}));sg.push(Ik);tg.unshift(function(a,b){eg(b,function(c){var d=zd(a),e=G(c,"settings.sm"),f=Yh(a);(d||e||f.id)&&rk(a,b,c)})});
function Rk(a,b,c,d){var e=this;return V(window,"c.i",function(){function f(w){(w=th(k,m,"",w)(k,m))&&(z(w.then)?w.then(g):g(w));return w}function g(w){w&&(z(w)?n.push(w):Ra(w)&&J(function(D){var B=p(D);D=B.next().value;B=B.next().value;z(B)&&("u"===D?n.push(B):h(B,D))},Rb(w)))}function h(w,D,B){e[D]=Mk(k,m,B||q,D,w)}var k=window;(!k||isNaN(a)&&!a)&&be();var l=oc(a,b,c,d),m=pc(l);qk(m).yc=l;Gg(m,m.G||{});var n=[],q=[Lk,th,Kk];q.unshift(pg);var r=J(x,tg);l=O(m);m.id||xc(vc("Invalid Metrika id: "+m.id,
!0));var v=Nk.m("counters",{});if(v[l])return r={},hg(k,l,"dc",(r.key=l,r)),v[l];v[l]=e;Nk.A("counters",v);Nk.O("counter",e);J(function(w){w(k,m)},qg);J(f,rg);f(kg);h(Jk(k,m,n),"destruct",[Lk,Kk]);jg(k,A([k,r,f,1,"a.i"],sj));J(f,sg);l={};Ed(k,(l.counterKey=O(m),l.name="counter",l.data=Sd(m),l))})()}J(oa(Nd)(window),vg);if(window.Ya&&Rk){var Sk=N.bc;window.Ya[Sk]=Rk;ng(window);J(F(ab([window,window.Ya[Sk]]),Nd),ug)};}).call(this);
